In [206]:
# Packages

import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go


# Variables Globales

WIDTH = 1024
HEIGHT = 800
SWIDTH = 1024
SHEIGHT = 800
FEMALE = '#ec4899'
MALE = '#646ffb'

In [207]:
# Chargement du fichier CSV

df = pd.read_csv("Speed_Dating_Data.csv", encoding='ISO-8859-1')

In [208]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Columns: 195 entries, iid to amb5_3
dtypes: float64(174), int64(13), object(8)
memory usage: 12.5+ MB

In [209]:
# Description du dataframe df

df.describe()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field_cd,race,imprace,imprelig,goal,date,go_out,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8296.000000,8315.000000,8299.000000,8299.000000,8299.000000,8281.000000,8299.000000,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,7.662488,2.757186,3.784793,3.651645,2.122063,5.006762,2.158091,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,3.758935,1.230905,2.845708,2.805237,1.407181,1.444531,1.105246,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,5.000000,2.000000,1.000000,1.000000,1.000000,4.000000,1.000000,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,8.000000,2.000000,3.000000,3.000000,2.000000,5.000000,2.000000,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,10.000000,4.000000,6.000000,6.000000,2.000000,6.000000,3.000000,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,18.000000,6.000000,10.000000,10.000000,6.000000,7.000000,7.000000,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [210]:
# Nombre de lignes et de colonnes
print(f"(nombre de Lignes, nombre de Colonnes) : {df.shape}")

(nombre de Lignes, nombre de Colonnes) : (8378, 195)

In [211]:
# Calcul du pourcentage de valeurs manquantes par colonne

pourcentage_manquant = df.isnull().mean() * 100

# Affichage des résultats

print("Pourcentage de valeurs manquantes par colonne :")
print(pourcentage_manquant)

# Pourcentage total de valeurs manquantes dans tout le DataFrame
pourcentage_total_manquant = df.isnull().mean().mean() * 100
print(f"\nPourcentage total de valeurs manquantes dans le DataFrame : {pourcentage_total_manquant:.2f}%")

Pourcentage de valeurs manquantes par colonne :
iid          0.000000
id           0.011936
gender       0.000000
idg          0.000000
condtn       0.000000
              ...
attr5_3     75.936978
sinc5_3     75.936978
intel5_3    75.936978
fun5_3      75.936978
amb5_3      75.936978
Length: 195, dtype: float64

Pourcentage total de valeurs manquantes dans le DataFrame : 26.44%

In [212]:
import pandas as pd

# Calcul du nombre de colonnes avec des valeurs manquantes
nombre_colonnes_manquantes = df.isnull().any().sum()

# Affichage du résultat
print(f"Nombre de colonnes avec des valeurs manquantes : {nombre_colonnes_manquantes} soit {round((nombre_colonnes_manquantes / df.shape[1]) * 100, 2)}% au total")

Nombre de colonnes avec des valeurs manquantes : 182 soit 93.33% au total

In [213]:
#Librairy Skimpy donne un aperçu plus complet que Describe
from skimpy import skim
skim(df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 8378   │ │ float64     │ 174   │                                                          │
│ │ Number of columns │ 195    │ │ int64       │ 13    │                                                          │
│ └───────────────────┴────────┘ │ string      │ 8     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┓  │
│ ┃ column    ┃ NA    ┃ NA %                ┃ mean   ┃ sd     ┃ p0    ┃ p25   ┃ p50   ┃ p75   ┃ p100  ┃ hist   ┃  │
│ ┡━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━┩  │
│ │ iid       │     0 │                   0 │  283.7 │  158.6 │     1 │   154 │   281 │   407 │   552 │ ▇▆█▇▇█ │  │
│ │ id        │     1 │   0.011936022917164 │   8.96 │  5.491 │     1 │     4 │     8 │    13 │    22 │ █▆▇▄▄▂ │  │
│ │ gender    │     0 │                   0 │ 0.5006 │    0.5 │     0 │     0 │     1 │     1 │     1 │ █    █ │  │
│ │ idg       │     0 │                   0 │  17.33 │  10.94 │     1 │     8 │    16 │    26 │    44 │ █▇▆▅▄▂ │  │
│ │ condtn    │     0 │                   0 │  1.829 │ 0.3767 │     1 │     2 │     2 │     2 │     2 │ ▂    █ │  │
│ │ wave      │     0 │                   0 │  11.35 │  5.996 │     1 │     7 │    11 │    15 │    21 │ ▆▃▄█▄▆ │  │
│ │ round     │     0 │                   0 │  16.87 │  4.358 │     5 │    14 │    18 │    20 │    22 │ ▁▃ ▅▅█ │  │
│ │ position  │     0 │                   0 │  9.043 │  5.515 │     1 │     4 │     8 │    13 │    22 │ █▆▇▄▄▂ │  │
│ │ positin1  │  1846 │  22.033898305084747 │  9.296 │   5.65 │     1 │     4 │     9 │    14 │    22 │ █▆▇▄▄▂ │  │
│ │ order     │     0 │                   0 │  8.928 │  5.477 │     1 │     4 │     8 │    13 │    22 │ █▆▇▄▄▂ │  │
│ │ partner   │     0 │                   0 │  8.964 │  5.491 │     1 │     4 │     8 │    13 │    22 │ █▆▇▄▄▂ │  │
│ │ pid       │    10 │    0.11936022917164 │  283.9 │  158.6 │     1 │   154 │   281 │   408 │   552 │ ▇▆█▇▇█ │  │
│ │ match     │     0 │                   0 │ 0.1647 │ 0.3709 │     0 │     0 │     0 │     0 │     1 │ █    ▂ │  │
│ │ int_corr  │   158 │   1.885891620911912 │  0.196 │ 0.3035 │ -0.83 │ -0.02 │  0.21 │  0.43 │  0.91 │  ▂▅█▇▂ │  │
│ │ samerace  │     0 │                   0 │ 0.3958 │ 0.4891 │     0 │     0 │     0 │     1 │     1 │ █    ▅ │  │
│ │ age_o     │   104 │  1.2413463833850562 │  26.36 │  3.564 │    18 │    24 │    26 │    28 │    55 │  ▅█▁   │  │
│ │ race_o    │    73 │   0.871329672952972 │  2.757 │  1.231 │     1 │     2 │     2 │     4 │     6 │ ▁█▁▃ ▁ │  │
│ │ pf_o_att  │    89 │   1.062306039627596 │   22.5 │  12.57 │     0 │    15 │    20 │    25 │   100 │  ▅█▁▁  │  │
│ │ pf_o_sin  │    89 │   1.062306039627596 │   17.4 │  7.044 │     0 │    15 │ 18.37 │    20 │    60 │  ▁█▇▁  │  │
│ │ pf_o_int  │    89 │   1.062306039627596 │  20.27 │  6.783 │     0 │ 17.39 │    20 │ 23.81 │    50 │   ▃█▃  │  │
│ │ pf_o_fun  │    98 │  1.1697302458820722 │  17.46 │  6.086 │     0 │    15 │    18 │    20 │    50 │  ▁▆█▂  │  │
│ │ pf_o_amb  │   107 │   1.277154452136548 │  10.69 │  6.127 │     0 │     5 │    10 │    15 │    53 │  ▄█▂   │  │
│ │ pf_o_sha  │   129 │  1.5397469563141561 │  11.85 │  6.363 │     0 │  9.52 │ 10.64 │    16 │    30 │ ▂▃█▆▃  │  │
│ │ dec_o     │     0 │                   0 │ 0.4196 │ 0.4935 │     0 │     0 │     0 │     1 │     1 │ █    ▆ │  │
│ │ attr_o    │   212 │  2.5304368584387684 │   6.19 │   1.95 │     0 │     5 │     6 │     8 │  10.5 │  ▂▆▅█▂ │  │
│ │ sinc_o    │   287 │  3.4256385772260685 │  7.175 │  1.741 │     0 │     6 │     7 │     8 │    10 │   ▁▄█▃ │  │
│ │ intel_o   │   306 │  3.6524230126521844 │  7.369 │  1.551 │     0 │     6 │     7 │     8 │    10 │    ▃█▃ │  │
│ │ fun_o     │   360 │   4.296968250179041 │  6.401 │  1.954 │     0 │     5 │     7 │     8 │    11 │  ▁▄█▅▁ │  │
│ │ amb_o     │   722 │   8.617808546192409 │  6.778 │  1.794 │     0 │     6 │     7 │     8 │    10 │  ▁▁▆█▃ │  │
│ │ shar_o    │  1076 │  12.843160658868465 │  5.475 │  2.156 │     0 │     4 │     6 │     7 │    10 │ ▁▃▂█▆▂ │  │
│ │ like_o    │   250 │  2.9840057292910003 │  6.134 │  1.841 │     0 │     5 │     6 │     7 │    10 │  ▂▂██▂ │  │
│ │ prob_o    │   318 │  3.7956552876581524 │  5.208 │  2.129 │     0 │     4 │     5 │     7 │    10 │ ▁▃▂█▄▁ │  │
│ │ met_o     │   385 │    4.59536882310814 │   1.96 │ 0.2459 │     1 │     2 │     2 │     2 │     8 │   █    │  │
│ │ age       │    95 │    1.13392217713058 │  26.36 │  3.567 │    18 │    24 │    26 │    28 │    55 │  ▅█▁   │  │
│ │ field_cd  │    82 │   0.978753879207448 │  7.662 │  3.759 │     1 │     5 │     8 │    10 │    18 │ ▄▄█▄▃  │  │
│ │ race      │    63 │   0.751969443781332 │  2.757 │  1.231 │     1 │     2 │     2 │     4 │     6 │ ▁█▁▃ ▁ │  │
│ │ imprace   │    79 │   0.942945810455956 │  3.785 │  2.846 │     0 │     1 │     3 │     6 │    10 │ █▆▁▃▃▂ │  │
│ │ imprelig  │    79 │   0.942945810455956 │  3.652 │  2.805 │     1 │     1 │     3 │     6 │    10 │ █▂▃▁▂▁ │  │
│ │ goal      │    79 │   0.942945810455956 │  2.122 │  1.407 │     1 │     1 │     2 │     2 │     6 │ █▇▁▁▁▁ │  │
│ │ date      │    97 │   1.157794222964908 │  5.007 │  1.445 │     1 │     4 │     5 │     6 │     7 │  ▁▂▅▃█ │  │
│ │ go_out    │    79 │   0.942945810455956 │  2.158 │  1.105 │     1 │     1 │     2 │     3 │     7 │  ▇█▅▁  │  │
│ │ career_c  │   138 │   1.647171162568632 │  5.278 │   3.31 │     1 │     2 │     6 │     7 │    17 │  █▃▅▃  │  │
│ │ sports    │    79 │   0.942945810455956 │  6.425 │  2.619 │     1 │     4 │     7 │     9 │    10 │ ▃▂▅▂█▇ │  │
│ │ tvsports  │    79 │   0.942945810455956 │  4.575 │  2.802 │     1 │     2 │     4 │     7 │    10 │ █▃▅▂▅▃ │  │
│ │ exercise  │    79 │   0.942945810455956 │  6.246 │  2.419 │     1 │     5 │     6 │     8 │    10 │ ▂▂▅▄█▅ │  │
│ │ dining    │    79 │   0.942945810455956 │  7.784 │  1.755 │     1 │     7 │     8 │     9 │    10 │   ▂▂█▇ │  │
│ │ museums   │    79 │   0.942945810455956 │  6.986 │  2.052 │     0 │     6 │     7 │     9 │    10 │  ▁▁▄█▅ │  │
│ │ art       │    79 │   0.942945810455956 │  6.715 │  2.263 │     0 │     5 │     7 │     8 │    10 │  ▂▁▅█▅ │  │
│ │ hiking    │    79 │   0.942945810455956 │  5.737 │   2.57 │     0 │     4 │     6 │     8 │    10 │ ▂▆▂▇█▄ │  │
│ │ gaming    │    79 │   0.942945810455956 │  3.881 │  2.621 │     0 │     2 │     3 │     6 │    14 │  █▄▄▃  │  │
│ │ clubbing  │    79 │   0.942945810455956 │  5.746 │  2.502 │     0 │     4 │     6 │     8 │    10 │ ▂▃▂▆█▃ │  │
│ │ reading   │    79 │   0.942945810455956 │  7.679 │  2.007 │     1 │     7 │     8 │     9 │    13 │  ▁▃▇█  │  │
│ │ tv        │    79 │   0.942945810455956 │  5.304 │  2.529 │     1 │     3 │     6 │     7 │    10 │ ▆▃█▅█▃ │  │
│ │ theater   │    79 │   0.942945810455956 │  6.776 │  2.235 │     0 │     5 │     7 │     9 │    10 │  ▂▁▅█▆ │  │
│ │ movies    │    79 │   0.942945810455956 │   7.92 │  1.701 │     0 │     7 │     8 │     9 │    10 │    ▂██ │  │
│ │ concerts  │    79 │   0.942945810455956 │  6.825 │  2.156 │     0 │     5 │     7 │     8 │    10 │  ▂▁▆█▅ │  │
│ │ music     │    79 │   0.942945810455956 │  7.851 │  1.792 │     1 │     7 │     8 │     9 │    10 │   ▂▂▇█ │  │
│ │ shopping  │    79 │   0.942945810455956 │  5.631 │  2.609 │     1 │     4 │     6 │     8 │    10 │ ▆▂▇▄█▅ │  │
│ │ yoga      │    79 │   0.942945810455956 │  4.339 │  2.718 │     0 │     2 │     4 │     7 │    10 │ ▆█▃▆▅▃ │  │
│ │ exphappy  │   101 │   1.205538314633564 │  5.534 │  1.734 │     1 │     5 │     6 │     7 │    10 │ ▁▂█▆▆▁ │  │
│ │ expnum    │  6578 │    78.5151587491048 │  5.571 │  4.763 │     0 │     2 │     4 │     8 │    20 │ █▅▁▂▁▁ │  │
│ │ attr1_1   │    79 │   0.942945810455956 │  22.51 │  12.59 │     0 │    15 │    20 │    25 │   100 │  ▅█▁▁  │  │
│ │ sinc1_1   │    79 │   0.942945810455956 │   17.4 │  7.047 │     0 │    15 │ 18.18 │    20 │    60 │  ▁█▇▁  │  │
│ │ intel1_1  │    79 │   0.942945810455956 │  20.27 │  6.783 │     0 │ 17.39 │    20 │ 23.81 │    50 │   ▃█▃  │  │
│ │ fun1_1    │    89 │   1.062306039627596 │  17.46 │  6.085 │     0 │    15 │    18 │    20 │    50 │  ▁▆█▂  │  │
│ │ amb1_1    │    99 │   1.181666268799236 │  10.68 │  6.125 │     0 │     5 │    10 │    15 │    53 │  ▄█▂   │  │
│ │ shar1_1   │   121 │  1.4442587729768441 │  11.85 │  6.362 │     0 │  9.52 │ 10.64 │    16 │    30 │ ▂▃█▆▃  │  │
│ │ attr4_1   │  1889 │  22.547147290522798 │  26.39 │   16.3 │     5 │    10 │    25 │    35 │    95 │  ▆█▂▂  │  │
│ │ sinc4_1   │  1889 │  22.547147290522798 │  11.07 │  6.659 │     0 │     6 │    10 │    15 │    35 │ ▄█▃▃ ▁ │  │
│ │ intel4_1  │  1889 │  22.547147290522798 │  12.64 │  6.717 │     0 │     8 │    10 │    16 │    35 │ ▂█▄▃▁▁ │  │
│ │ fun4_1    │  1889 │  22.547147290522798 │  15.57 │  7.328 │     0 │    10 │    15 │    20 │    45 │ ▂▆█▁▁  │  │
│ │ amb4_1    │  1889 │  22.547147290522798 │   9.78 │  6.998 │     0 │     5 │    10 │    15 │    50 │  ██▂▁  │  │
│ │ shar4_1   │  1911 │  22.809739794700405 │  11.01 │   6.06 │     0 │     7 │    10 │    15 │    40 │  ▄█▃▃  │  │
│ │ attr2_1   │    79 │   0.942945810455956 │  30.36 │  16.25 │     0 │    20 │    25 │    40 │   100 │  ▂█▂▂  │  │
│ │ sinc2_1   │    79 │   0.942945810455956 │  13.27 │  6.977 │     0 │    10 │    15 │ 18.75 │    50 │  ▄█▄▁  │  │
│ │ intel2_1  │    79 │   0.942945810455956 │  14.42 │  6.263 │     0 │    10 │    15 │    20 │    40 │ ▂██▆▁  │  │
│ │ fun2_1    │    79 │   0.942945810455956 │  18.42 │  6.578 │     0 │    15 │    20 │    20 │    50 │  ▁▆█▃  │  │
│ │ amb2_1    │    89 │   1.062306039627596 │  11.74 │  6.887 │     0 │     6 │    10 │    15 │    50 │  ▄█▂▁  │  │
│ │ shar2_1   │    89 │   1.062306039627596 │  11.85 │  6.167 │     0 │    10 │    10 │ 15.63 │    30 │ ▂▃█▅▂▁ │  │
│ │ attr3_1   │   105 │    1.25328240630222 │  7.085 │  1.396 │     2 │     6 │     7 │     8 │    10 │   ▁█▄▂ │  │
│ │ sinc3_1   │   105 │    1.25328240630222 │  8.295 │  1.407 │     2 │     8 │     8 │     9 │    10 │    ▃▄█ │  │
│ │ fun3_1    │   105 │    1.25328240630222 │  7.704 │  1.564 │     2 │     7 │     8 │     9 │    10 │ ▁ ▁█▇█ │  │
│ │ intel3_1  │   105 │    1.25328240630222 │  8.404 │  1.077 │     3 │     8 │     8 │     9 │    10 │    ▂▆█ │  │
│ │ amb3_1    │   105 │    1.25328240630222 │  7.578 │  1.778 │     2 │     7 │     8 │     9 │    10 │ ▁▁▂▇▆█ │  │
│ │ attr5_1   │  3472 │   41.44187156839341 │  6.942 │  1.499 │     2 │     6 │     7 │     8 │    10 │ ▁ ▁█▄▂ │  │
│ │ sinc5_1   │  3472 │   41.44187156839341 │  7.927 │  1.627 │     1 │     7 │     8 │     9 │    10 │   ▁▂█▇ │  │
│ │ intel5_1  │  3472 │   41.44187156839341 │  8.284 │  1.284 │     3 │     8 │     8 │     9 │    10 │   ▁▃▅█ │  │
│ │ fun5_1    │  3472 │   41.44187156839341 │  7.426 │  1.779 │     2 │     6 │     8 │     9 │    10 │ ▁▁▁█▅▇ │  │
│ │ amb5_1    │  3472 │   41.44187156839341 │  7.618 │  1.773 │     1 │     7 │     8 │     9 │    10 │   ▂▂█▇ │  │
│ │ dec       │     0 │                   0 │ 0.4199 │ 0.4936 │     0 │     0 │     0 │     1 │     1 │ █    ▆ │  │
│ │ attr      │   202 │   2.411076629267128 │   6.19 │   1.95 │     0 │     5 │     6 │     8 │    10 │  ▂▂██▂ │  │
│ │ sinc      │   277 │   3.306278348054428 │  7.175 │   1.74 │     0 │     6 │     7 │     8 │    10 │   ▁▄█▃ │  │
│ │ intel     │   296 │   3.533062783480544 │  7.369 │   1.55 │     0 │     6 │     7 │     8 │    10 │    ▃█▃ │  │
│ │ fun       │   350 │  4.1776080210074005 │  6.401 │  1.954 │     0 │     5 │     7 │     8 │    10 │  ▁▂▇█▃ │  │
│ │ amb       │   712 │   8.498448317020769 │  6.778 │  1.794 │     0 │     6 │     7 │     8 │    10 │  ▁▁▆█▃ │  │
│ │ shar      │  1067 │  12.735736452613988 │  5.475 │  2.156 │     0 │     4 │     6 │     7 │    10 │ ▁▃▂█▆▂ │  │
│ │ like      │   240 │    2.86464550011936 │  6.134 │  1.841 │     0 │     5 │     6 │     7 │    10 │  ▂▂██▂ │  │
│ │ prob      │   309 │  3.6882310814036763 │  5.208 │   2.13 │     0 │     4 │     5 │     7 │    10 │ ▁▃▂█▄▁ │  │
│ │ met       │   375 │     4.4760085939365 │ 0.9488 │ 0.9899 │     0 │     0 │     0 │     2 │     8 │   █▇   │  │
│ │ match_es  │  1173 │  14.000954881833373 │  3.208 │  2.445 │     0 │     2 │     3 │     4 │    18 │  █▇▂▁  │  │
│ │ attr1_s   │  4282 │  51.110050131296255 │  20.79 │  12.97 │     3 │ 14.81 │ 17.65 │    25 │    95 │  █▆▁▁  │  │
│ │ sinc1_s   │  4282 │  51.110050131296255 │  15.43 │  6.915 │     0 │    10 │ 15.79 │    20 │    50 │  ▃██▁  │  │
│ │ intel1_s  │  4282 │  51.110050131296255 │  17.24 │  6.596 │     0 │    10 │ 18.42 │    20 │    40 │ ▁▅█▇▂  │  │
│ │ fun1_s    │  4282 │  51.110050131296255 │  15.26 │  5.357 │     1 │    10 │ 15.91 │    20 │    40 │  ▁▄█▁  │  │
│ │ amb1_s    │  4282 │  51.110050131296255 │  11.14 │  5.514 │     0 │     7 │    10 │    15 │ 23.81 │ ▂▅█▆▄▂ │  │
│ │ shar1_s   │  4282 │  51.110050131296255 │  12.46 │  5.922 │     0 │     9 │  12.5 │ 16.28 │    30 │ ▂▅█▇▃▁ │  │
│ │ attr3_s   │  4378 │  52.255908331343996 │  7.211 │  1.415 │     3 │     7 │     7 │     8 │    10 │ ▁▂▃██▃ │  │
│ │ sinc3_s   │  4378 │  52.255908331343996 │  8.082 │  1.456 │     1 │     7 │     8 │     9 │    10 │   ▁▁█▇ │  │
│ │ intel3_s  │  4378 │  52.255908331343996 │  8.258 │  1.179 │     4 │     8 │     8 │     9 │    10 │  ▁ ▃▆█ │  │
│ │ fun3_s    │  4378 │  52.255908331343996 │  7.692 │  1.627 │     3 │     7 │     8 │     9 │    10 │ ▁▁▂▆▆█ │  │
│ │ amb3_s    │  4378 │  52.255908331343996 │  7.589 │  1.793 │     2 │     7 │     8 │     9 │    10 │ ▁▁▂▆▅█ │  │
│ │ satis_2   │   915 │   10.92146096920506 │  5.712 │  1.821 │     1 │     5 │     6 │     7 │    10 │ ▂▂▇▇█▁ │  │
│ │ length    │   915 │   10.92146096920506 │  1.843 │ 0.9757 │     1 │     1 │     1 │     3 │     3 │ █    ▆ │  │
│ │ numdat_2  │   945 │  11.279541656719982 │  2.338 │ 0.6312 │     1 │     2 │     2 │     3 │     3 │ ▁  █ ▇ │  │
│ │ attr7_2   │  6394 │   76.31893053234663 │  32.82 │  17.16 │    10 │    20 │    30 │    40 │    80 │ █▆▃▃▂▁ │  │
│ │ sinc7_2   │  6423 │   76.66507519694437 │  13.53 │  7.977 │     0 │    10 │    10 │    20 │    40 │  ▅█▄▇  │  │
│ │ intel7_2  │  6394 │   76.31893053234663 │  15.29 │  7.293 │     0 │    10 │    15 │    20 │    50 │  ▁█▅▁  │  │
│ │ fun7_2    │  6394 │   76.31893053234663 │  18.87 │  8.536 │     0 │    10 │    20 │    24 │    50 │ ▁█▆▄▁  │  │
│ │ amb7_2    │  6423 │   76.66507519694437 │  7.287 │  6.125 │     0 │     0 │     5 │    10 │    20 │ ██ ▇▄▂ │  │
│ │ shar7_2   │  6404 │   76.43829076151826 │  12.16 │  8.242 │     0 │     5 │    10 │    20 │    40 │ █▆▄▅▁  │  │
│ │ attr1_2   │   933 │  11.136309381714012 │  26.22 │  14.39 │     5 │ 16.67 │    20 │    30 │    85 │ ▅█▁▁▁  │  │
│ │ sinc1_2   │   915 │   10.92146096920506 │  15.87 │  6.658 │     0 │    10 │ 16.67 │    20 │    50 │  ▂██▂  │  │
│ │ intel1_2  │   915 │   10.92146096920506 │  17.81 │  6.536 │     0 │    15 │ 19.05 │    20 │    40 │ ▁▃▇█▁  │  │
│ │ fun1_2    │   915 │   10.92146096920506 │  17.65 │   6.13 │     0 │    15 │ 18.37 │    20 │    50 │  ▁▇█▂  │  │
│ │ amb1_2    │   915 │   10.92146096920506 │  9.913 │  5.676 │     0 │     5 │    10 │    15 │ 22.22 │ ▃▄█▂▅▂ │  │
│ │ shar1_2   │   915 │   10.92146096920506 │  12.76 │  6.652 │     0 │    10 │    13 │ 16.67 │    35 │ ▅██▄▁▁ │  │
│ │ attr4_2   │  2603 │  31.069467653377895 │  26.81 │   16.4 │     6 │    10 │    25 │    40 │   100 │  █▅▄   │  │
│ │ sinc4_2   │  2603 │  31.069467653377895 │  11.93 │  6.402 │     0 │     8 │    10 │    15 │    35 │  ▂█▃▃  │  │
│ │ intel4_2  │  2603 │  31.069467653377895 │   12.1 │  5.991 │     0 │     8 │    10 │    15 │    40 │  ▃█▄▃  │  │
│ │ fun4_2    │  2603 │  31.069467653377895 │  15.16 │   7.29 │     0 │     9 │    15 │    20 │    50 │  ▄█▆▂  │  │
│ │ amb4_2    │  2603 │  31.069467653377895 │  9.343 │  5.856 │     0 │     5 │    10 │    10 │    35 │  ▅█▂▁  │  │
│ │ shar4_2   │  2603 │  31.069467653377895 │  11.32 │  6.296 │     0 │     7 │    10 │    15 │    40 │  ▄█▃▃  │  │
│ │ attr2_2   │  2603 │  31.069467653377895 │  29.34 │  14.55 │     0 │ 19.15 │    25 │ 38.46 │    85 │ ▁█▄▁▁  │  │
│ │ sinc2_2   │  2603 │  31.069467653377895 │   13.9 │  6.172 │     0 │    10 │    15 │ 19.23 │    40 │  ▃▆█▅  │  │
│ │ intel2_2  │  2603 │  31.069467653377895 │  13.96 │  5.399 │     0 │    10 │    15 │ 17.39 │ 30.77 │ ▂▇▆█▁  │  │
│ │ fun2_2    │  2603 │  31.069467653377895 │  17.97 │    6.1 │     0 │    15 │ 18.52 │    20 │    40 │ ▁▃██▁  │  │
│ │ amb2_2    │  2603 │  31.069467653377895 │  11.91 │  6.313 │     0 │    10 │    10 │ 15.09 │    50 │  ▃█▂   │  │
│ │ shar2_2   │  2603 │  31.069467653377895 │  12.89 │  5.616 │     0 │    10 │ 13.95 │ 16.52 │    30 │ ▁▂█▇▃  │  │
│ │ attr3_2   │   915 │   10.92146096920506 │  7.125 │  1.371 │     2 │     7 │     7 │     8 │    10 │   ▁█▅▂ │  │
│ │ sinc3_2   │   915 │   10.92146096920506 │  7.932 │  1.503 │     2 │     7 │     8 │     9 │    10 │   ▁▆▆█ │  │
│ │ intel3_2  │   915 │   10.92146096920506 │  8.239 │   1.18 │     4 │     8 │     8 │     9 │    10 │   ▁▃▆█ │  │
│ │ fun3_2    │   915 │   10.92146096920506 │  7.602 │  1.548 │     1 │     7 │     8 │     9 │    10 │   ▁▁█▄ │  │
│ │ amb3_2    │   915 │   10.92146096920506 │  7.487 │  1.745 │     2 │     7 │     8 │     9 │    10 │ ▁▁▁█▆▇ │  │
│ │ attr5_2   │  4001 │  47.756027691573166 │  6.828 │  1.411 │     2 │     6 │     7 │     8 │    10 │ ▁ ▁█▃▁ │  │
│ │ sinc5_2   │  4001 │  47.756027691573166 │  7.394 │  1.588 │     2 │     6 │     8 │     8 │    10 │ ▁ ▁█▇▅ │  │
│ │ intel5_2  │  4001 │  47.756027691573166 │  7.839 │  1.281 │     2 │     7 │     8 │     9 │    10 │   ▁██▇ │  │
│ │ fun5_2    │  4001 │  47.756027691573166 │  7.279 │  1.647 │     2 │     6 │     7 │     8 │    10 │  ▁▁█▅▄ │  │
│ │ amb5_2    │  4001 │  47.756027691573166 │  7.332 │  1.522 │     2 │     6 │     7 │     8 │    10 │   ▁█▄▄ │  │
│ │ you_call  │  4404 │   52.56624492719026 │ 0.7808 │  1.612 │     0 │     0 │     0 │     1 │    21 │   █    │  │
│ │ them_cal  │  4404 │   52.56624492719026 │ 0.9816 │  1.382 │     0 │     0 │     1 │     1 │     9 │  █▁▁   │  │
│ │ date_3    │  4404 │   52.56624492719026 │  0.377 │ 0.4847 │     0 │     0 │     0 │     1 │     1 │ █    ▅ │  │
│ │ numdat_3  │  6882 │   82.14370971592265 │  1.231 │  1.295 │     0 │     1 │     1 │     1 │     9 │  █▁▁   │  │
│ │ num_in_3  │  7710 │   92.02673669133445 │ 0.9341 │ 0.7539 │     0 │     1 │     1 │     1 │     4 │  ▃█ ▁  │  │
│ │ attr1_3   │  4404 │   52.56624492719026 │  24.38 │  13.71 │     0 │ 15.22 │    20 │    30 │    80 │  ▁█▁▂  │  │
│ │ sinc1_3   │  4404 │   52.56624492719026 │  16.59 │  7.472 │     0 │    10 │ 16.67 │    20 │    65 │  ▃█▁   │  │
│ │ intel1_3  │  4404 │   52.56624492719026 │  19.41 │  6.125 │     0 │ 16.67 │    20 │    20 │    45 │  ▁█▁▁  │  │
│ │ fun1_3    │  4404 │   52.56624492719026 │  16.23 │  5.164 │     0 │ 14.81 │ 16.33 │    20 │    30 │  ▁▄█▅▁ │  │
│ │ amb1_3    │  4404 │   52.56624492719026 │   10.9 │  5.901 │     0 │     5 │    10 │    15 │    30 │ ▃▄██▁  │  │
│ │ shar1_3   │  4404 │   52.56624492719026 │   12.7 │  6.557 │     0 │    10 │ 14.29 │ 16.67 │    55 │  ▃█▂   │  │

In [214]:
# La librairie Summary tools donne un aperçu d'une façon différente
#from summarytools import dfSummary
#dfSummary(df)

In [215]:
df['age'] = df['age'].fillna(df['age'].median())
df['field'] = df['field'].fillna('Non spécifié')

In [216]:
# Vérifier les colonnes nécessaires
if 'age' in df.columns and 'gender' in df.columns:

    # Créer une version catégorielle du genre pour l'affichage
    df['gender_label'] = df['gender'].map({0: 'FEMALE', 1: 'MALE'})

    # Histogramme interactif avec Plotly Express
    fig = px.histogram(df,
                       x='age',
                       color='gender_label',
                       nbins=20,
                       title="Distribution de l'âge selon le sexe",
                       labels={'age': 'Âge', 'gender_label': 'Sexe'},
                       category_orders={'gender_label': ['Femme', 'Homme']},
                       opacity=0.8,
                       color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
                       width=SWIDTH,  # Largeur en pixels
                        height=SHEIGHT, # Hauteur en pixels,  # Spécifier les couleurs ici
)
    fig.update_layout(barmode='overlay')
    fig.show()
else:
    print("Les colonnes 'age' et/ou 'gender' sont manquantes dans le dataset.")

In [217]:

# Vérifier que la colonne 'race' existe
if 'race' in df.columns:

    # Compter la fréquence de chaque race
    race_counts = df['race'].value_counts().reset_index()
    race_counts.columns = ['Race', 'Count']

    # Mapping correct des races
    race_labels = {
        1: 'Black',
        2: 'European',
        3: 'Latino',
        4: 'Asian',
        5: 'Native American',
        6: 'Other'
    }

    # Remplacer les codes par les labels
    race_counts['Race'] = race_counts['Race'].map(race_labels).fillna('Inconnu')

    # Calculer les pourcentages
    race_counts['Pourcentage'] = (race_counts['Count'] / race_counts['Count'].sum()) * 100
    race_counts['Pourcentage'] = race_counts['Pourcentage'].round(2)

    # Afficher la répartition
    print("Répartition des races (en pourcentage) :")
    print(race_counts[['Race', 'Count', 'Pourcentage']])

    # Camembert interactif avec Plotly
    fig = px.pie(
        race_counts,
        names='Race',
        values='Count',
        title="Répartition des ethnies parmi les participants",
        color_discrete_sequence=px.colors.qualitative.Plotly,
       width=SWIDTH,  # Largeur en pixels
        height=SHEIGHT,
    )

    fig.update_traces(textinfo='percent+label')
    fig.show()

else:
    print("La colonne 'race' n’existe pas dans le dataset. Vérifie le nom des colonnes.")

Répartition des races (en pourcentage) :
       Race  Count  Pourcentage
0  European   4727        56.85
1     Asian   1982        23.84
2    Latino    664         7.99
3     Other    522         6.28
4     Black    420         5.05

In [218]:
# Création d'un score global d'attractivité
trait_cols = ['attr1_1', 'sinc1_1', 'intel1_1', 'fun1_1', 'amb1_1']
df['total_attraction_score'] = df[trait_cols].sum(axis=1)
#Taux de match par participant
df['match_ratio'] = df.groupby('iid')['match'].transform(lambda x: x.mean())

In [219]:
df

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3,gender_label,total_attraction_score,match_ratio
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,552,22.0,1,44,2,21,22,14,10.0,5,18,526.0,0,0.64,0,26.0,3.0,10.0,10.0,30.0,20.0,10.0,15.0,1,10.0,5.0,3.0,2.0,6.0,5.0,6.0,1.0,NaN,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,3.0,5.0,5.0,5.0,NaN,NaN,2.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727
8374,552,22.0,1,44,2,21,22,13,10.0,4,19,527.0,0,0.71,0,24.0,6.0,50.0,20.0,10.0,5.0,10.0,5.0,0,6.0,3.0,7.0,3.0,7.0,2.0,2.0,2.0,2.0,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,4.0,6.0,8.0,4.0,4.0,NaN,4.0,4.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727
8375,552,22.0,1,44,2,21,22,19,10.0,10,20,528.0,0,-0.46,0,29.0,3.0,40.0,10.0,30.0,10.0,10.0,NaN,0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,4.0,7.0,8.0,8.0,8.0,NaN,6.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727
8376,552,22.0,1,44,2,21,22,3,10.0,16,21,529.0,0,0.62,0,22.0,4.0,10.0,25.0,25.0,10.0,10.0,20.0,1,5.0,7.0,5.0,5.0,3.0,6.0,6.0,4.0,2.0,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,4.0,6.0,5.0,4.0,NaN,5.0,5.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727
8377,552,NaN,1,44,2,21,22,2,10.0,15,22,530.0,0,0.01,0,22.0,4.0,20.0,20.0,10.0,15.0,5.0,30.0,1,8.0,8.0,7.0,7.0,7.0,7.0,8.0,5.0,2.0,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,3.0,7.0,6.0,4.0,8.0,1.0,4.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727

In [220]:
age_match = df.groupby('age')['match'].mean().reset_index()
fig = px.line(age_match, x='age', y='match', title="Taux de match par âge", width=SWIDTH,  # Largeur en pixels
                        height=SHEIGHT,)
fig.show()

In [ ]:
# Dans la distribution il n'y a plus d'homme au delà de 42, on exclut aussi les femmes au-delà de cette âge
# Vérifier que les colonnes nécessaires sont présentes
if 'age' in df.columns and 'gender' in df.columns and 'match' in df.columns:
    # Filtrer jusqu'à 42 ans inclus
    df_filtered = df[df['age'] <= 36]

    # Calculer le taux de match par âge et par sexe
    age_gender_match = df_filtered.groupby(['age', 'gender'])['match'].mean().reset_index()

    # Renommer pour plus de lisibilité dans la légende
    age_gender_match['gender_label'] = age_gender_match['gender'].map({0: 'FEMALE', 1: 'MALE'})

    # Graphique interactif avec Plotly
    fig = px.line(
        age_gender_match,
        x='age',
        y='match',
        color='gender_label',
        title="Taux de match par âge et par sexe (jusqu'à 42 ans)",
        labels={'match': 'Taux de match moyen', 'age': 'Âge', 'gender_label': 'Sexe'},
        range_x=[age_gender_match['age'].min(), 36],
        color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
        width=SWIDTH,  # Largeur en pixels
        height=SHEIGHT,
    )

    fig.update_layout(
        legend_title_text='Sexe',
        xaxis_title='Âge',
        yaxis_title='Taux de match'
    )

    fig.show()
else:
    print("Les colonnes nécessaires ('age', 'gender', 'match') ne sont pas toutes présentes.")

In [222]:
nouveaux_labels_o = ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt communs "]

In [223]:
df['career'] = df['career'].str.lower()
df[['gender']] = df[['gender']].astype(str)

In [224]:
# Modification des valeurs en utilisant .loc
df.loc[df['gender'] == '0', 'gender'] = 'FEMALE'
df.loc[df['gender'] == '1', 'gender'] = 'MALE'

In [225]:
#Display all the columns
pd.options.display.max_columns = None
df

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3,gender_label,total_attraction_score,match_ratio
0,1,1.0,FEMALE,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
1,1,1.0,FEMALE,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
2,1,1.0,FEMALE,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
3,1,1.0,FEMALE,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
4,1,1.0,FEMALE,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN,FEMALE,85.0,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,552,22.0,MALE,44,2,21,22,14,10.0,5,18,526.0,0,0.64,0,26.0,3.0,10.0,10.0,30.0,20.0,10.0,15.0,1,10.0,5.0,3.0,2.0,6.0,5.0,6.0,1.0,NaN,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,3.0,5.0,5.0,5.0,NaN,NaN,2.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727
8374,552,22.0,MALE,44,2,21,22,13,10.0,4,19,527.0,0,0.71,0,24.0,6.0,50.0,20.0,10.0,5.0,10.0,5.0,0,6.0,3.0,7.0,3.0,7.0,2.0,2.0,2.0,2.0,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,4.0,6.0,8.0,4.0,4.0,NaN,4.0,4.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727
8375,552,22.0,MALE,44,2,21,22,19,10.0,10,20,528.0,0,-0.46,0,29.0,3.0,40.0,10.0,30.0,10.0,10.0,NaN,0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,1.0,2.0,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,4.0,7.0,8.0,8.0,8.0,NaN,6.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727
8376,552,22.0,MALE,44,2,21,22,3,10.0,16,21,529.0,0,0.62,0,22.0,4.0,10.0,25.0,25.0,10.0,10.0,20.0,1,5.0,7.0,5.0,5.0,3.0,6.0,6.0,4.0,2.0,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,4.0,6.0,5.0,4.0,NaN,5.0,5.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727
8377,552,NaN,MALE,44,2,21,22,2,10.0,15,22,530.0,0,0.01,0,22.0,4.0,20.0,20.0,10.0,15.0,5.0,30.0,1,8.0,8.0,7.0,7.0,7.0,7.0,8.0,5.0,2.0,25.0,Climate Dynamics,18.0,"Ecole Normale Suprieure, Paris",NaN,NaN,2.0,1.0,1.0,France,"78,110",NaN,1.0,2.0,1.0,assistant master of the universe (otherwise it...,15.0,8.0,2.0,5.0,10.0,10.0,10.0,7.0,1.0,9.0,8.0,3.0,7.0,9.0,10.0,10.0,7.0,3.0,10.0,NaN,70.0,0.0,15.0,15.0,0.0,0.0,90.0,0.0,0.0,0.0,0.0,10.0,50.0,0.0,0.0,30.0,0.0,20.0,8.0,7.0,6.0,7.0,7.0,9.0,7.0,10.0,5.0,9.0,0,3.0,7.0,6.0,4.0,8.0,1.0,4.0,5.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,1.0,2.0,70.0,0.0,15.0,10.0,0.0,5.0,70.00,0.00,15.00,10.00,0.00,5.00,80.0,0.0,5.0,5.0,0.0,10.0,50.0,5.0,10.0,20.0,5.0,10.0,9.0,3.0,7.0,6.0,9.0,9.0,3.0,9.0,4.0,7.0,2.0,0.0,0.0,NaN,1.0,70.0,0.0,20.0,10.0,0.0,0.0,70.0,0.0,20.0,10.0,0.0,0.0,80.0,0.0,10.0,0.0,0.0,10.0,50.0,5.0,10.0,20.0,10.0,5.0,8.0,5.0,7.0,6.0,7.0,9.0,5.0,9.0,5.0,6.0,MALE,100.0,0.272727

In [226]:
match = df['match'].value_counts().reset_index()

match

   match  count
0      0   6998
1      1   1380

In [227]:
labels = ['No Match', 'Match']
values = [6998, 1380]
colors = [MALE, FEMALE]  

fig = go.Figure(data=[go.Pie(
    labels=labels,
    values=values,
    pull=[0, 0.2],
    texttemplate='<em>%{label}</em><br> <b>%{percent}</b>',
    textfont_size=15,
    textfont_color="yellow",
    marker_colors=colors  
)])

fig.update_layout(
    width=1024,  # Largeur en pixels
    height=600,  # Hauteur en pixels
    legend=dict(
        title='Légende',  # Titre de la légende
        x=1,  
        y=1,  
        bgcolor='rgba(255, 255, 255, 0.7)',  
        bordercolor='rgba(0, 0, 0, 0.5)', 
        borderwidth=1 
    )
)

fig.show()

In [228]:
# Filtrer les métiers exercés par les hommes
male_df = df[df['gender'] == 'MALE']

# Filtrer les métiers exercés par les femmes
female_df = df[df['gender'] == 'FEMALE']

# Compter les occurrences de chaque métier pour les hommes
male_career_counts = male_df['career'].value_counts().reset_index()
male_career_counts.columns = ['career', 'MALE']

# Compter les occurrences de chaque métier pour les femmes
female_career_counts = female_df['career'].value_counts().reset_index()
female_career_counts.columns = ['career', 'FEMALE']

# Fusionner les deux dataframes sur la colonne 'career' (inner join pour les métiers communs)
common_careers_df = pd.merge(male_career_counts, female_career_counts, on='career', how='inner')

# Affichage du dataframe résultant
print("DataFrame des métiers communs avec le nombre d'occurrences par genre :")
common_careers_df

DataFrame des métiers communs avec le nombre d'occurrences par genre :

                    career  MALE  FEMALE
0               consulting   215       9
1                professor   191     156
2                  finance   172      56
3                   lawyer   156     102
4       investment banking   123      20
5                      law   116      82
6                 business    95      62
7                 academic    70      67
8                 academia    61      21
9                 research    58      22
10   management consulting    58      10
11               scientist    57      65
12                 banking    52      31
13               undecided    36      84
14                  writer    34      49
15                medicine    29      36
16                teaching    22       5
17               physician    22      36
18                 writing    21       9
19              researcher    20      42
20              journalist    20      10
21                engineer    19      37
22            screenwriter    18      19
23         english teacher    15      14
24          writer/teacher    15      19
25                attorney    10      10
26  international business    10      20
27           writer/editor     6      38
28          epidemiologist     6      42

In [229]:
px.bar(
    common_careers_df,
    x='career',
    y=['MALE', 'FEMALE'],
    barmode='group',
    title="Carrière souhaitée selon le Sexe",
    width=1400,
    height=600,
    color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE}
)

In [ ]:
# Nettoyage des lignes potentiellement mal formatées 
df = df[df['gender'].isin(['MALE', 'FEMALE'])]
df = df[df['career'].astype(str).str.isalpha()]

# Filtrer le DataFrame pour ne garder que les hommes
male_df = df[df['gender'] == 'MALE']

# Filtrer le DataFrame pour ne garder que les femmes
female_df = df[df['gender'] == 'FEMALE']

# Obtenir la liste des métiers féminins uniques
female_unique_careers = female_df['career'].unique()

# Compter les occurrences de chaque métier exercé par les hommes
male_career_counts = male_df['career'].value_counts().reset_index()
male_career_counts.columns = ['career', 'nombre_hommes']

# Filtrer ce DataFrame pour ne garder que les métiers qui ne sont PAS dans la liste des métiers féminins uniques
only_male_careers_df = male_career_counts[~male_career_counts['career'].isin(female_unique_careers)]

# Affichage du DataFrame des métiers exercés uniquement par les hommes avec leur nombre
print("DataFrame des métiers exercés uniquement par les hommes avec le nombre d'hommes :")
print(only_male_careers_df)

DataFrame des métiers exercés uniquement par les hommes avec le nombre d'hommes :
          career  nombre_hommes
6   entrepreneur             73
14          film             33
15        banker             29
17        trader             27
18       science             22
19        doctor             22
21    management             22
23  enterpreneur             21
26          hero             20
28           ceo             20
30   engineering             18
32   millionaire             18
33     marketing             18
34           tba             16
35      politics             15
36       acadeic             15
37  cardiologist             10
38      novelist             10
39       trading             10
41    pediatrics             10
42   entrepeneur             10
43   academician             10
44    healthcare             10
45      diplomat             10
46    naturalist              9
47        energy              6
48      lobbyist              6
49    consultant              6
50        unsure              6
52           mba              5

In [231]:
fig_man_career_exclusif = px.bar(only_male_careers_df, x = 'career', y ='nombre_hommes', title="Carrière souhaitée <b>uniquement</b> par les hommes", width=WIDTH, height=HEIGHT)
fig_man_career_exclusif.update_traces(marker_color='#6366f1')
fig_man_career_exclusif.show()

In [232]:
# Filtrer le DataFrame pour ne garder que les hommes
male_df = df[df['gender'] == 'MALE']

# Filtrer le DataFrame pour ne garder que les femmes
female_df = df[df['gender'] == 'FEMALE']

# Obtenir la liste des métiers masculins uniques
male_unique_careers = male_df['career'].unique()

# Compter les occurrences de chaque métier exercé par les femmes
female_career_counts = female_df['career'].value_counts().reset_index()
female_career_counts.columns = ['career', 'nombre_femmes']

# Filtrer ce DataFrame pour ne garder que les métiers qui ne sont PAS dans la liste des métiers masculins uniques
only_female_careers_df = female_career_counts[~female_career_counts['career'].isin(male_unique_careers)]

# Affichage du DataFrame des métiers exercés uniquement par les femmes avec leur nombre
print("DataFrame des métiers exercés uniquement par les femmes avec le nombre de femmes :")
print(only_female_careers_df)

DataFrame des métiers exercés uniquement par les femmes avec le nombre de femmes :
              career  nombre_femmes
2            teacher             95
6            actress             66
8       psychologist             64
9          education             63
15        journalism             40
20          educator             23
21            acting             22
24         dietician             21
25         historian             20
27         filmmaker             19
28   pharmaceuticals             18
29          governor             18
30            artist             18
31      nutritionist             18
32       informatics             16
33     biostatistics             16
34         nonprofit             16
35          planning             15
36           unknown             15
37         economist             10
40        comedienne             10
41         academics             10
44         president              9
45  entrepreneurship              6

In [233]:
fig_women_career_exclusif = px.bar(only_female_careers_df, x = 'career', y ='nombre_femmes', title="Carrière souhaitée <b>uniquement</b> par les femmes", width=WIDTH, height=HEIGHT)
fig_women_career_exclusif.update_traces(marker_color='#ec4899')
fig_women_career_exclusif.show()

In [234]:

# Nettoyage basique
df['career'] = df['career'].str.lower().str.strip()  # Normalisation
df['satis_2'] = pd.to_numeric(df['satis_2'], errors='coerce')

# Filtrer les lignes avec des valeurs valides
df_filtered = df.dropna(subset=['career', 'satis_2'])

# Calculer la satisfaction moyenne par carrière
satisfaction_by_career = df_filtered.groupby('career')['satis_2'].mean().reset_index()

# Trier par satisfaction décroissante
satisfaction_by_career = satisfaction_by_career.sort_values(by='satis_2', ascending=False)

# Afficher un graphique interactif avec Plotly Express
fig = px.bar(
    satisfaction_by_career,
    x='career',
    y='satis_2',
    title="Satisfaction moyenne par carrière après l'événement",
    labels={'career': 'Carrière', 'satis_2': 'Satisfaction moyenne'},
    height=600,
    width=1000
)

fig.update_layout(xaxis_tickangle=-45)
fig.show()

In [235]:
ethnie_m_counts = male_df['imprace'].mean()
ethnie_f_counts = female_df['imprace'].mean()
ethnie_data = {
        "GENDER" : ['MALE', 'FEMALE'],
        "Count" : [ethnie_m_counts, ethnie_f_counts]}


ethnie_df = pd.DataFrame(ethnie_data)

In [236]:
ethnie_df

   GENDER     Count
0    MALE  3.280518
1  FEMALE  3.912426

In [237]:
px.bar(ethnie_df, x = "GENDER", y = 'Count', color = 'GENDER', width=SWIDTH, height=SHEIGHT, title="L'importance de l'Ethnie dans le choix du Partenaire", color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})

In [238]:
relig_m_counts = male_df['imprelig'].mean()
relig_f_counts = female_df['imprelig'].mean()
relig_data = {
        "GENDER" : ['MALE', 'FEMALE'],
        "Count" : [relig_m_counts, relig_f_counts]}


relig_df = pd.DataFrame(ethnie_data)

In [239]:
px.bar(relig_df, x = "GENDER", y = 'Count', color = 'GENDER', width=SWIDTH, height=SHEIGHT, title="L'importance de la Religion dans le choix du Partenaire", color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})

In [240]:
column_names = list(df.columns)
column_names

['iid',
 'id',
 'gender',
 'idg',
 'condtn',
 'wave',
 'round',
 'position',
 'positin1',
 'order',
 'partner',
 'pid',
 'match',
 'int_corr',
 'samerace',
 'age_o',
 'race_o',
 'pf_o_att',
 'pf_o_sin',
 'pf_o_int',
 'pf_o_fun',
 'pf_o_amb',
 'pf_o_sha',
 'dec_o',
 'attr_o',
 'sinc_o',
 'intel_o',
 'fun_o',
 'amb_o',
 'shar_o',
 'like_o',
 'prob_o',
 'met_o',
 'age',
 'field',
 'field_cd',
 'undergra',
 'mn_sat',
 'tuition',
 'race',
 'imprace',
 'imprelig',
 'from',
 'zipcode',
 'income',
 'goal',
 'date',
 'go_out',
 'career',
 'career_c',
 'sports',
 'tvsports',
 'exercise',
 'dining',
 'museums',
 'art',
 'hiking',
 'gaming',
 'clubbing',
 'reading',
 'tv',
 'theater',
 'movies',
 'concerts',
 'music',
 'shopping',
 'yoga',
 'exphappy',
 'expnum',
 'attr1_1',
 'sinc1_1',
 'intel1_1',
 'fun1_1',
 'amb1_1',
 'shar1_1',
 'attr4_1',
 'sinc4_1',
 'intel4_1',
 'fun4_1',
 'amb4_1',
 'shar4_1',
 'attr2_1',
 'sinc2_1',
 'intel2_1',
 'fun2_1',
 'amb2_1',
 'shar2_1',
 'attr3_1',
 'sinc3_1',
 'fun3_1',
 'intel3_1',
 'amb3_1',
 'attr5_1',
 'sinc5_1',
 'intel5_1',
 'fun5_1',
 'amb5_1',
 'dec',
 'attr',
 'sinc',
 'intel',
 'fun',
 'amb',
 'shar',
 'like',
 'prob',
 'met',
 'match_es',
 'attr1_s',
 'sinc1_s',
 'intel1_s',
 'fun1_s',
 'amb1_s',
 'shar1_s',
 'attr3_s',
 'sinc3_s',
 'intel3_s',
 'fun3_s',
 'amb3_s',
 'satis_2',
 'length',
 'numdat_2',
 'attr7_2',
 'sinc7_2',
 'intel7_2',
 'fun7_2',
 'amb7_2',
 'shar7_2',
 'attr1_2',
 'sinc1_2',
 'intel1_2',
 'fun1_2',
 'amb1_2',
 'shar1_2',
 'attr4_2',
 'sinc4_2',
 'intel4_2',
 'fun4_2',
 'amb4_2',
 'shar4_2',
 'attr2_2',
 'sinc2_2',
 'intel2_2',
 'fun2_2',
 'amb2_2',
 'shar2_2',
 'attr3_2',
 'sinc3_2',
 'intel3_2',
 'fun3_2',
 'amb3_2',
 'attr5_2',
 'sinc5_2',
 'intel5_2',
 'fun5_2',
 'amb5_2',
 'you_call',
 'them_cal',
 'date_3',
 'numdat_3',
 'num_in_3',
 'attr1_3',
 'sinc1_3',
 'intel1_3',
 'fun1_3',
 'amb1_3',
 'shar1_3',
 'attr7_3',
 'sinc7_3',
 'intel7_3',
 'fun7_3',
 'amb7_3',
 'shar7_3',
 'attr4_3',
 'sinc4_3',
 'intel4_3',
 'fun4_3',
 'amb4_3',
 'shar4_3',
 'attr2_3',
 'sinc2_3',
 'intel2_3',
 'fun2_3',
 'amb2_3',
 'shar2_3',
 'attr3_3',
 'sinc3_3',
 'intel3_3',
 'fun3_3',
 'amb3_3',
 'attr5_3',
 'sinc5_3',
 'intel5_3',
 'fun5_3',
 'amb5_3',
 'gender_label',
 'total_attraction_score',
 'match_ratio']

In [241]:
x = ["attr1_1", "sinc1_1", "intel1_1", "fun1_1", "amb1_1", "shar1_1"]

# Définir les nouveaux labels pour l'axe des x

nouveaux_labels_o = ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt communs "]

fig = px.box(df, x,
             color = "gender",
            title= "Critères d'attraction: <b>ce que l'on recherche 🔍 chez l'autre </b> ",
            labels=nouveaux_labels_o,
            width=WIDTH, height=HEIGHT, color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})


# Mettre à jour les labels de l'axe des x
fig.update_layout(
    yaxis=dict(
        tickmode='array',  # Utiliser un tableau personnalisé pour les ticks
        tickvals=x,       # Les valeurs actuelles de l'axe des x
        ticktext=nouveaux_labels_o, # Les nouveaux labels correspondants
        title_text="Critères d'attraction"  # Titre de l'axe X 
    ),
     xaxis=dict(
        title_text="Points"  # Titre de l'axe Y
)
)
fig.show()

ici on remarqe que la Séduction (Attractiveness) vient en premier quelque soit le sexe, ensuite l'intelligence, en 3e la sincérité, en queue de peloton les points communs.

In [242]:
#Before Dating
# mettre .copy() pour éviter l'alerte d'erreur
before_dating = df[['gender', "attr1_1", "sinc1_1", "intel1_1", "fun1_1", "amb1_1", "shar1_1"]].copy()

# renommer les colonnes pour obtenir une courbe avec des légendes adaptées
before_dating.rename(columns={"gender": "Gender", "attr1_1" : "Attractivité", "sinc1_1" : "Sincérité", "intel1_1" : "Intelligence", "fun1_1" : "Fun", "amb1_1" : "Ambition", "shar1_1": "Centres d'intérêt communs"}, inplace=True)

# Calculer la moyenne par genre
df_mean = before_dating.groupby('Gender').mean().reset_index()

# Pivoter la table
df_melted = df_mean.melt(id_vars=['Gender'], var_name='Trait', value_name='Moyenne')
df_melted = df_melted.sort_values(by="Moyenne", ascending=False)

# Créer une liste des critères triés
sorted_traits = df_melted['Trait'].unique()

# Création du graphique avec `barmode='group'`
fig = px.bar(df_melted, x='Trait', y='Moyenne', color='Gender', barmode='group',
             title="Les critères souhaités avant le Dating", opacity=0.9, 
             labels={'Moyenne': 'Mean Of Points', 'Trait': 'Les critères notées'},
             category_orders={"Trait": sorted_traits}, width=1400, height=600, color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})

# Forcer un espace entre les barres pour éviter l'empilement visuel
fig.update_layout(bargap=0.2)

# Affichage
fig.show()

In [243]:
#Before Dating
# mettre .copy() pour éviter l'alerte d'erreur

after_match = df[df['dec'] == 1]

after_dating = after_match[['gender', "attr", "sinc", "intel", "fun", "amb", "shar"]]

# renommer les colonnes pour obtenir une courbe avec des légendes adaptées
after_dating.rename(columns={"gender": "Gender", "attr" : "Attractivité", "sinc" : "Sincérité", "intel" : "Intelligence", "fun" : "Fun", "amb" : "Ambition", "shar": "Centres d'intérêt communs"}, inplace=True)

# Calculer la moyenne par genre
df_mean_after = after_dating.groupby('Gender').mean().reset_index()

# Transformer en format long (pivot)
df_melted_after = df_mean_after.melt(id_vars=['Gender'], var_name='Trait', value_name='Moyenne')
df_melted_after = df_melted_after.sort_values(by="Moyenne", ascending=False)

# Créer une liste des critères triés
sorted_traits = df_melted['Trait'].unique()

# Création du graphique avec `barmode='group'`
fig = px.bar(df_melted_after, x='Trait', y='Moyenne', color='Gender', barmode='group',
             title="Les critères après la volonté de Matcher", opacity=0.9, 
             labels={'Moyenne': 'Mean Of Points', 'Trait': 'Les critères'},
             category_orders={"Trait": sorted_traits}, width=1400, height=600, color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})

# Forcer un espace entre les barres pour éviter l'empilement visuel
fig.update_layout(bargap=0.2)

# Affichage
fig.show()

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/1699924490.py:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [244]:
# Filtrer les lignes où 'dec' == 1 ET 'dec_o' == 1
after_match = df[(df['dec'] == 1) & (df['dec_o'] == 1)].copy()
# Sélectionner les colonnes pertinentes
after_dating = after_match[['gender', 'attr', 'sinc', 'intel', 'fun', 'amb', 'shar']]
# Renommer les colonnes pour plus de lisibilité
after_dating.rename(columns={
    'gender': 'Gender',
    'attr': 'Attractivité',
    'sinc': 'Sincérité',
    'intel': 'Intelligence',
    'fun': 'Fun',
    'amb': 'Ambition',
    'shar': 'Centres d\'intérêt communs'
}, inplace=True)
# Calculer la moyenne par genre
df_mean_after = after_dating.groupby('Gender').mean().reset_index()
# Transformer en format long pour Plotly
df_melted_after = df_mean_after.melt(id_vars=['Gender'],
                                     value_vars=['Attractivité', 'Sincérité', 'Intelligence', 'Fun', 'Ambition', 'Centres d\'intérêt communs'],
                                     var_name='Trait',
                                     value_name='Moyenne')
# Trier les traits par moyenne décroissante
df_melted_after = df_melted_after.sort_values(by="Moyenne", ascending=False)
# Créer le graphique avec Plotly Express
fig = px.bar(
    df_melted_after,
    x='Trait',
    y='Moyenne',
    color='Gender',
    barmode='group',
    title="Les critères après la volonté de Matcher",
    labels={'Moyenne': 'Moyenne des points', 'Trait': 'Critères'},
    width=1000,
    height=600,
    color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
)
# Améliorer l'affichage
fig.update_layout(bargap=0.2)
fig.show()

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/2379038406.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [245]:

# Filtrer les matchs mutuels
match_mutuel = df[(df['dec'] == 1) & (df['dec_o'] == 1)].copy()

# Sélectionner les colonnes pertinentes : race du participant et race du partenaire
match_race = match_mutuel[['race', 'race_o']].copy()

# Optionnel : ajouter une colonne indiquant si les deux personnes sont de la même race
match_race['samerace'] = (match_race['race'] == match_race['race_o']).astype(int)

# Renommer les colonnes pour plus de lisibilité
match_race.rename(columns={
    'race': 'Race du participant',
    'race_o': 'Race du partenaire',
    'samerace': 'Même race ?'
}, inplace=True)

# Afficher les premières lignes
print("Matchs mutuels avec race du participant et du partenaire :")
print(match_race.head())

# Optionnel : compter combien de matchs sont entre personnes de même race
same_race_count = match_race['Même race ?'].sum()
total_matches = len(match_race)
print(f"\nNombre de matchs mutuels : {total_matches}")
print(f"Nombre de matchs entre personnes de même race : {same_race_count}")
print(f"Pourcentage de matchs avec même race : {same_race_count / total_matches * 100:.2f}%")

Matchs mutuels avec race du participant et du partenaire :
    Race du participant  Race du partenaire  Même race ?
2                   4.0                 4.0            1
3                   4.0                 2.0            0
4                   4.0                 3.0            0
8                   4.0                 2.0            0
13                  2.0                 2.0            1

Nombre de matchs mutuels : 646
Nombre de matchs entre personnes de même race : 243
Pourcentage de matchs avec même race : 37.62%

In [246]:
# Filtrer les matchs mutuels (participant ET partenaire ont dit "oui")
match_mutuel = df[(df['dec'] == 1) & (df['dec_o'] == 1) & (df['gender'] =='FEMALE')]

# Compter combien de matchs sont entre personnes de même race ou non
same_race_count = match_mutuel[match_mutuel['samerace'] == 1].shape[0]
diff_race_count = match_mutuel[match_mutuel['samerace'] == 0].shape[0]

# Créer un DataFrame pour Plotly
pie_df = pd.DataFrame({
    'Catégorie': ['Même ethnie', 'Ethnie différente'],
    'Nombre de matchs': [same_race_count, diff_race_count]
})

# Créer le camembert avec Plotly Express
fig = px.pie(
    pie_df,
    names='Catégorie',
    values='Nombre de matchs',
    title="Répartition des matchs mutuels :même ethnie vs différente ethnie chez la Femme",
    color_discrete_sequence=['#ab47bc', FEMALE],  
    width=1024,
    height=700
)

# Mettre à jour la taille et la couleur des caractères à l'intérieur du camembert
fig.update_traces(
    textinfo='percent+label',
    textfont=dict(
        size=18,  # Taille de la police
        color='white'  # Couleur de la police
    )
)
fig.show()

In [247]:
# Filtrer les matchs mutuels (participant ET partenaire ont dit "oui")
match_mutuel = df[(df['dec'] == 1) & (df['dec_o'] == 1) & (df['gender'] =='MALE')]

# Compter combien de matchs sont entre personnes de même race ou non
same_race_count = match_mutuel[match_mutuel['samerace'] == 1].shape[0]
diff_race_count = match_mutuel[match_mutuel['samerace'] == 0].shape[0]

# Créer un DataFrame pour Plotly
pie_df = pd.DataFrame({
    'Catégorie': ['Même ethnie', 'Ethnie différente'],
    'Nombre de matchs': [same_race_count, diff_race_count]
})

# Créer le camembert avec Plotly Express
fig = px.pie(
    pie_df,
    names='Catégorie',
    values='Nombre de matchs',
    title="Répartition des matchs mutuels : même ethnie vs différente ethnie chez l'homme",
    color_discrete_sequence=[MALE, '#48b2e3'],  
    width=1024,
    height=700
)

fig.update_traces(
    textinfo='percent+label',
    textfont=dict(
        size=18,  # Taille de la police
        color='white'  # Couleur de la police
    )
)
fig.show()

In [248]:
# Mapping des races selon le .doc
race_labels = {
    1: 'Black',
    2: 'European',
    3: 'Latino',
    4: 'Asian',
    5: 'Native American',
    6: 'Other'
}

# Filtrer les matchs mutuels où les deux personnes ne sont pas de la même race
df_match = df[df['match'] == 1]  # Match mutuel
df_cross_race = df_match[df_match['samerace'] == 0]  # Races différentes

# Remplacer les codes par des labels
df_cross_race['race_label'] = df_cross_race['race'].map(race_labels)
df_cross_race['race_o_label'] = df_cross_race['race_o'].map(race_labels)

# Supprimer les lignes avec race ou race_o manquantes (NaN)
df_cross_race.dropna(subset=['race_label', 'race_o_label'], inplace=True)

# Créer une combinaison raciale (participant x partenaire) - triée pour éviter les doublons comme "A x B" et "B x A"
df_cross_race['Combination'] = df_cross_race[['race_label', 'race_o_label']].apply(lambda x: ' x '.join(sorted(x)), axis=1)

# Créer un DataFrame groupé par genre et combinaison raciale
combination_df = df_cross_race.groupby(['gender', 'Combination']).size().reset_index(name='Count')

# Calculer le total par genre pour normaliser les pourcentages
total_by_gender = combination_df.groupby('gender')['Count'].transform('sum')
combination_df['Pourcentage'] = (combination_df['Count'] / total_by_gender) * 100
combination_df['Pourcentage'] = combination_df['Pourcentage'].round(2)

# Camembert (sunburst) interactif par genre et combinaison raciale
fig_sunburst = px.sunburst(
    combination_df,
    path=['gender', 'Combination'],
    values='Count',
    title="Répartition des combinaisons des ethnies dans les matchs de ethnies différentes (ventilé par genre)",
    color='gender',
    color_discrete_map={'FEMALE': '#FF69B4', 'MALE': '#1E90FF'}
)

fig_sunburst.show()

# Graphique à barres groupées
fig_bar = px.bar(
    combination_df,
    x='Combination',
    y='Pourcentage',
    color='gender',
    barmode='group',
    title="Matchs de ethnies différentes – Répartition en % par genre",
    labels={'Pourcentage': 'Pourcentage (%)', 'Combination': 'Combinaison raciale'},
    color_discrete_map={'FEMALE': '#FF69B4', 'MALE': '#1E90FF'},
    width=1000,
    height=600
)

fig_bar.update_layout(xaxis_tickangle=-45, legend_title_text='Genre')
fig_bar.show()

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/3196344871.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/3196344871.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/3196344871.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/3196344871.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [249]:
# Colonnes des traits recherchés
trait_cols = ['attr', 'sinc', 'intel', 'fun', 'amb', 'shar']

# Filtrer les matchs mutuels ET où les deux personnes sont de la même race
df_same_race = df[(df['match'] == 1) & (df['samerace'] == 1)]

# Vérifier que les colonnes existent
for col in trait_cols:
    if col not in df_same_race.columns:
        raise ValueError(f"La colonne {col} est manquante dans le dataset.")

# Renommer les colonnes pour plus de lisibilité (optionnel)
df_same_race.rename(columns={
    'attr': 'Attractivité',
    'sinc': 'Sincérité',
    'intel': 'Intelligence',
    'fun': 'Fun',
    'amb': 'Ambition',
    'shar': 'Centres d’intérêt'
}, inplace=True)

# Transformer en format long pour Plotly
df_long = df_same_race.melt(id_vars='gender',
                            value_vars=['Attractivité', 'Sincérité', 'Intelligence', 'Fun', 'Ambition', 'Centres d’intérêt'],
                            var_name='Critère',
                            value_name='Points')

# Calculer les moyennes par genre et par critère
df_avg = df_long.groupby(['gender', 'Critère'])['Points'].mean().reset_index()

# Afficher les moyennes sous forme de graphique à barres groupées
fig = px.bar(
    df_avg,
    x='Critère',
    y='Points',
    color='gender',
    barmode='group',
    title="Critères recherchés dans les matchs de même race (matchs mutuels)",
    labels={'Points': 'Points moyens attribués', 'Critère': 'Critère d’attraction'},
    color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
    width=900,
    height=600
)

fig.update_layout(
    xaxis_tickangle=-45,
    legend_title_text='Genre'
)

fig.show()

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/587618835.py:13: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [250]:
# Colonnes clés
if 'you_call' in df.columns and 'match' in df.columns and 'gender' in df.columns:

    # Calculer la proportion de matchs contactés par participant
    df['proportion_contact'] = df['you_call'] / df['match'].replace(0, pd.NA)

    # Remplacer les NaN par 0 (match == 0 → division par zéro)
    df['proportion_contact'] = df['proportion_contact'].fillna(0)

    # Afficher les statistiques descriptives
    print("Statistiques descriptives de la proportion de matchs contactés :")
    print(df.groupby('gender')['proportion_contact'].describe())

    # Graphique à barres groupées : moyenne par genre
    gender_avg = df.groupby('gender')['proportion_contact'].mean().reset_index()
    gender_avg['proportion_contact'] = gender_avg['proportion_contact'].round(2)

    # Graphique à barres avec Plotly
    fig = px.bar(
        gender_avg,
        x='gender',
        y='proportion_contact',
        title="Après l'évènement, qui fait l'action de contacter ? ",
        labels={'proportion_contact': 'Proportion de matchs contactés', 'gender': 'Genre'},
        color='gender',
        color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
        width=800,
        height=500
    )

    fig.update_layout(showlegend=False)
    fig.show()

else:
    print("Les colonnes nécessaires (you_call, match, gender) ne sont pas présentes.")

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/2627431597.py:8: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Statistiques descriptives de la proportion de matchs contactés :
         count      mean       std  min  25%  50%  75%  max
gender
FEMALE  1749.0  0.017153  0.150296  0.0  0.0  0.0  0.0  2.0
MALE    2027.0  0.146029  0.738444  0.0  0.0  0.0  0.0  8.0

In [251]:
# Colonnes clés
if 'you_call' in df.columns and 'match' in df.columns and 'gender' in df.columns:

    # Calculer la proportion de matchs contactés par participant
    df['proportion_contact'] = df['them_cal'] / df['match'].replace(0, pd.NA)

    # Remplacer les NaN par 0 (match == 0 → division par zéro)
    df['proportion_contact'] = df['proportion_contact'].fillna(0)

    # Afficher les statistiques descriptives
    print("Statistiques descriptives de la proportion de matchs contactés :")
    print(df.groupby('gender')['proportion_contact'].describe())

    # Graphique à barres groupées : moyenne par genre
    gender_avg = df.groupby('gender')['proportion_contact'].mean().reset_index()
    gender_avg['proportion_contact'] = gender_avg['proportion_contact'].round(2)

    # Graphique à barres avec Plotly
    fig = px.bar(
        gender_avg,
        x='gender',
        y='proportion_contact',
        title="Proportion moyenne des matchs contactés après l'événement (you_call / match)",
        labels={'proportion_contact': 'Proportion de matchs contactés', 'gender': 'Genre'},
        color='gender',
        color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
        width=800,
        height=500
    )

    fig.update_layout(showlegend=False)
    fig.show()

else:
    print("Après l'évènement, qui est contacté ?")

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/2591588763.py:8: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Statistiques descriptives de la proportion de matchs contactés :
         count      mean       std  min  25%  50%  75%  max
gender
FEMALE  1749.0  0.191538  0.911042  0.0  0.0  0.0  0.0  9.0
MALE    2027.0  0.074988  0.494092  0.0  0.0  0.0  0.0  6.0

In [252]:
# Filtrer les lignes où 'dec' == 1 ET 'dec_o' == 1
after_match = df[(df['dec'] == 1)].copy()
# Sélectionner les colonnes pertinentes
after_dating = after_match[['gender', 'attr', 'sinc', 'intel', 'fun', 'amb', 'shar']]
# Renommer les colonnes pour plus de lisibilité
after_dating.rename(columns={
    'gender': 'Gender',
    'attr': 'Attractivité',
    'sinc': 'Sincérité',
    'intel': 'Intelligence',
    'fun': 'Fun',
    'amb': 'Ambition',
    'shar': 'Centres d\'intérêt communs'
}, inplace=True)
# Calculer la moyenne par genre
df_mean_after = after_dating.groupby('Gender').mean().reset_index()
# Transformer en format long pour Plotly
df_melted_after = df_mean_after.melt(id_vars=['Gender'],
                                     value_vars=['Attractivité', 'Sincérité', 'Intelligence', 'Fun', 'Ambition', 'Centres d\'intérêt communs'],
                                     var_name='Trait',
                                     value_name='Moyenne')
# Trier les traits par moyenne décroissante
df_melted_after = df_melted_after.sort_values(by="Moyenne", ascending=False)
# Créer le graphique avec Plotly Express
fig = px.bar(
    df_melted_after,
    x='Trait',
    y='Moyenne',
    color='Gender',
    barmode='group',
    title="Les critères après la volonté de Matcher du participant",
    labels={'Moyenne': 'Moyenne des points', 'Trait': 'Critères'},
    width=1400,
    height=600,
    color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
)
# Améliorer l'affichage
fig.update_layout(bargap=0.2)
fig.show()

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/3104267640.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [253]:
# Filtrer les lignes où 'dec' == 1 ET 'dec_o' == 1
after_match = df[(df['dec'] == 1) & (df['dec_o'] == 1)].copy()
# Sélectionner les colonnes pertinentes
after_dating = after_match[['gender', 'attr', 'sinc', 'intel', 'fun', 'amb', 'shar']]
# Renommer les colonnes pour plus de lisibilité
after_dating.rename(columns={
    'gender': 'Gender',
    'attr': 'Attractivité',
    'sinc': 'Sincérité',
    'intel': 'Intelligence',
    'fun': 'Fun',
    'amb': 'Ambition',
    'shar': 'Centres d\'intérêt communs'
}, inplace=True)
# Calculer la moyenne par genre
df_mean_after = after_dating.groupby('Gender').mean().reset_index()
# Transformer en format long pour Plotly
df_melted_after = df_mean_after.melt(id_vars=['Gender'],
                                     value_vars=['Attractivité', 'Sincérité', 'Intelligence', 'Fun', 'Ambition', 'Centres d\'intérêt communs'],
                                     var_name='Trait',
                                     value_name='Moyenne')
# Trier les traits par moyenne décroissante
df_melted_after = df_melted_after.sort_values(by="Moyenne", ascending=False)
# Créer le graphique avec Plotly Express
fig = px.bar(
    df_melted_after,
    x='Trait',
    y='Moyenne',
    color='Gender',
    barmode='group',
    title="Les critères après la volonté de Matcher des deux côtés",
    labels={'Moyenne': 'Moyenne des points', 'Trait': 'Critères'},
    width=1400,
    height=600,
    color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
)
# Améliorer l'affichage
fig.update_layout(bargap=0.2)
fig.show()

/var/folders/mk/k32g1gsn4c1_yd1vbqdbpvw00000gn/T/ipykernel_1978/3502162435.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [254]:
# Filtrer les matchs mutuels ET les personnes de même religion
match_mutuel_same_religion = df[
    (df['dec'] == 1) &
    (df['dec_o'] == 1) &
    (df['samerace'] == 0)
].copy()
# Sélectionner les colonnes pertinentes
after_dating = match_mutuel_same_religion[['gender', 'attr', 'sinc', 'intel', 'fun', 'amb', 'shar']].copy()
# Renommer les colonnes pour plus de lisibilité
after_dating.rename(columns={
    'gender': 'Gender',
    'attr': 'Attractivité',
    'sinc': 'Sincérité',
    'intel': 'Intelligence',
    'fun': 'Fun',
    'amb': 'Ambition',
    'shar': 'Centres d\'intérêt communs'
}, inplace=True)
# Calculer la moyenne par genre
df_mean_after = after_dating.groupby('Gender').mean().reset_index()
# Transformer en format long pour Plotly
df_melted_after = df_mean_after.melt(id_vars=['Gender'],
                                     value_vars=['Attractivité', 'Sincérité', 'Intelligence', 'Fun', 'Ambition', 'Centres d\'intérêt communs'],
                                     var_name='Trait',
                                     value_name='Moyenne')
# Trier les traits par moyenne décroissante
df_melted_after = df_melted_after.sort_values(by="Moyenne", ascending=False)
# Créer le graphique avec Plotly Express
fig = px.bar(
    df_melted_after,
    x='Trait',
    y='Moyenne',
    color='Gender',
    barmode='group',
    title="Critères recherchés dans les matchs mutuels entre personnes de différent ethnie",
    labels={'Moyenne': 'Points moyens attribués', 'Trait': 'Critères notées'},
    color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},  # Couleurs personnalisées
    width=1000,
    height=600
)
# Améliorer l'affichage
fig.update_layout(bargap=0.2)
fig.show()

In [255]:
satisfaction = df[['satis_2', 'gender']]

In [256]:
satisfaction = df.groupby('gender')['satis_2'].mean().reset_index()

In [257]:
satisfaction

   gender   satis_2
0  FEMALE  5.113907
1    MALE  6.001665

In [258]:

# Créer le graphique à barres avec les couleurs spécifiées
fig = px.bar(satisfaction, x='gender', y='satis_2', color='gender',
             color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE},
             width=SWIDTH, height=SHEIGHT,
             title="Le Degré de Satisfaction après le Dating", )

# Afficher le graphique
fig.show()

In [259]:

# Noter après la Satisfaction
value_sat = ["attr1_1", "sinc1_1", "intel1_1", "fun1_1", "amb1_1", 'shar1_1']
# Définir les nouveaux labels pour l'axe des x
labels_sat = ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt"]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"],
                    value_vars=value_sat,
                    var_name="Critère",
                    value_name="Points")

# Créer un dictionnaire de mapping
label_map = dict(zip(value_sat, labels_sat))
# Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Les critères recherchés avant le dating",
    width=WIDTH,
    height=HEIGHT
)

fig.show()

In [260]:
import pandas as pd
import plotly.graph_objects as go

# Colonnes représentant les traits attribués au partenaire
value_sat = ["attr", "sinc", "intel", "fun", "amb", "shar"]

# Labels pour l'affichage
labels_sat = ["Attractivité", "Sincérité", "Intelligence", "Fun", "Ambition", "Centres d'intérêt"]

# Filtrer uniquement les personnes qui ont dit "oui" pour matcher
df_yes = df[df['dec'] == 1]

# Melt pour obtenir un format long pour Plotly
df_melted = df_yes.melt(id_vars=["gender"],
                        value_vars=value_sat,
                        var_name="Critère",
                        value_name="Points")

# Remplacer les noms des critères par des labels lisibles
label_map = dict(zip(value_sat, labels_sat))
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Calculer la moyenne par genre et par critère
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

# Couleurs personnalisées
colors = {'FEMALE': '#FF69B4', 'MALE': '#1E90FF'}

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre : {gender}",
        line=dict(color=colors.get(gender, "grey")),
        hovertemplate="Critère: %{theta}<br>Note moyenne: %{r:.2f}"
    ))

# Mise en page du radar chart
fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max() + 5])),
    showlegend=True,
    title="Traits attribués au partenaire après avoir dit 'oui' pour matcher",
    legend_title="Genre",
    width=WIDTH,
    height=HEIGHT
)

fig.show()

In [261]:
import plotly.graph_objects as go

# Noter après la Satisfaction
value_sat = ["attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", 'shar7_2']
# Définir les nouveaux labels pour l'axe des x
labels_sat = ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt"]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"],
                    value_vars=value_sat,
                    var_name="Critère",
                    value_name="Points")

# Créer un dictionnaire de mapping
label_map = dict(zip(value_sat, labels_sat))
# Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Les critères qui comptent après la Note de la Satisfaction",
    width=WIDTH,
    height=HEIGHT
)

fig.show()

In [262]:
# Noter après la Satisfaction

value_sat= ["attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", 'shar7_2']

# Définir les nouveaux labels pour l'axe des x

labels_sat= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt"]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_sat,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_sat, labels_sat))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Les critères qui comptent après la Note de la Satisfaction ", width=WIDTH, height=HEIGHT
)

fig.show()

In [263]:
#filter satisfaction
satis_filter_happy = df[df['satis_2'] == 8]

# Noter après la Satisfaction

value_sat = ["attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", 'shar7_2']

# Définir les nouveaux labels pour l'axe des x

labels_sat= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt"]

# Supposons que df est votre DataFrame
df_melted = satis_filter_happy.melt(id_vars=["gender"], 
                    value_vars=value_sat,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_sat, labels_sat))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Ce qui compte même quand on est déçu par l'Expérience", width=WIDTH, height=HEIGHT
)

fig.show()

In [264]:
#filter satisfaction
satis_filter = df[df['satis_2'] == 2]

# Noter après la Satisfaction

value_sat = ["attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", 'shar7_2']

# Définir les nouveaux labels pour l'axe des x

labels_sat= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt"]

# Supposons que df est votre DataFrame
df_melted = satis_filter.melt(id_vars=["gender"], 
                    value_vars=value_sat,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_sat, labels_sat))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Ce qui compte même quand on est déçu par l'Expérience", width=WIDTH, height=HEIGHT
)

fig.show()

In [265]:
#filter satisfaction
satis_filter_happy = df[df['satis_2'] == 8]

# Noter après la Satisfaction

value_sat = ["attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", 'shar7_2']

# Définir les nouveaux labels pour l'axe des x

labels_sat= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt"]

# Supposons que df est votre DataFrame
df_melted = satis_filter_happy.melt(id_vars=["gender"], 
                    value_vars=value_sat,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_sat, labels_sat))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Ce qui compte quand on est content de l'Expérience", width=WIDTH, height=HEIGHT
)

fig.show()

In [266]:
# Ce que l'on croit que le sex opposé recherche

x = ["attr4_1", "sinc4_1", "intel4_1", "fun4_1", "amb4_1", "shar4_1"]

# Définir les nouveaux labels pour l'axe des x

nouveaux_labels_o = ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt communs "]

fig = px.box(df, x,
             color = "gender",
            title= "Critères d'attraction : <b>ce que l'on croit 🤔 que l'autre recherche chez le sexe opposé...</b>",
            labels=nouveaux_labels_o, width=WIDTH, height=HEIGHT, color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})


# Mettre à jour les labels de l'axe des x
fig.update_layout(
    yaxis=dict(
        tickmode='array',  # Utiliser un tableau personnalisé pour les ticks
        tickvals=x,       # Les valeurs actuelles de l'axe des x
        ticktext=nouveaux_labels_o, # Les nouveaux labels correspondants
        title_text="Critères d'attraction"  # Titre de l'axe X 
    ),
     xaxis=dict(
        title_text="Points"  # Titre de l'axe Y
)
)
fig.show()

In [267]:
# Ce que l'on pense que le sexe opposé recherche
x = ["attr2_1", "sinc2_1", "intel2_1", "fun2_1", "amb2_1", "shar2_1"]

nouveaux_labels_o = ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt communs "]

fig = px.box(df, x,
             color = "gender",
            title= "Critères d'attraction: <b>on pense ce que le sexe opposé recherche  🔍 pour une rencontre </b> ",
            labels=nouveaux_labels_o, width=WIDTH, height=HEIGHT, color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})


# Mettre à jour les labels de l'axe des x
fig.update_layout(
    yaxis=dict(
        tickmode='array',  # Utiliser un tableau personnalisé pour les ticks
        tickvals=x,       # Les valeurs actuelles de l'axe des x
        ticktext=nouveaux_labels_o, # Les nouveaux labels correspondants
        title_text="Critères d'attraction"  # Titre de l'axe X 
    ),
     xaxis=dict(
        title_text="Points"  # Titre de l'axe Y
)
)
fig.show()

In [268]:
# Ce que l'on pense de soi

x = ["attr3_1", "sinc3_1", "intel3_1", "fun3_1", "amb3_1"]

# Définir les nouveaux labels pour l'axe des x

nouveaux_labels_o = ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

fig = px.box(df, x,
             color = "gender",
            title= "Critères d'attraction : <b>ce que l'on pense de soi 🤩...</b> ",
            labels=nouveaux_labels_o, width=WIDTH, height=HEIGHT, color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})


# Mettre à jour les labels de l'axe des x
fig.update_layout(
    yaxis=dict(
        tickmode='array',  # Utiliser un tableau personnalisé pour les ticks
        tickvals=x,       # Les valeurs actuelles de l'axe des x
        ticktext=nouveaux_labels_o, # Les nouveaux labels correspondants
        title_text="Critères d'attraction"  # Titre de l'axe X 
    ),
     xaxis=dict(
        title_text="Points"  # Titre de l'axe Y
)
)
fig.show()

#ici on bascule à des notations sur de 1 à 10. L'échelle change mais il manque des données

In [269]:
# Ce que l'on pense de soi

value_soi= ["attr3_1", "sinc3_1", "intel3_1", "fun3_1", "amb3_1"]

# Définir les nouveaux labels pour l'axe des x

labels_soi= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_soi,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_soi, labels_soi))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Ce que l'on pense de soi ", width=WIDTH, height=HEIGHT
)

fig.show()

In [270]:
# Ce que les autres pensent nous 

value_autres= ["attr5_1", "sinc5_1", "intel5_1", "fun5_1", "amb5_1"]

# Définir les nouveaux labels pour l'axe des x

labels_autres= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_autres,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_autres, labels_autres))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Ce que les autres pensent de nous", width=WIDTH, height=HEIGHT
)

fig.show()

In [271]:
# A la moitié de l'expérience

value_autres_half= ["attr1_s", "sinc1_s", "intel1_s", "fun1_s", "amb1_s", "shar1_s"]

# Définir les nouveaux labels pour l'axe des x

labels_autres= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition", "Centre d'intérêts communs"]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_autres_half,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_autres_half, labels_autres))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Attentes à la moitié de l'expérience ", width=WIDTH, height=HEIGHT
)

fig.show()

In [272]:
# Ce qui est important dans la décision

value_YesNo= ["attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", 'shar7_2']

# Définir les nouveaux labels pour l'axe des x

labels_YesNo= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition ", "Centres d'intérêt communs "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_YesNo,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_YesNo, labels_YesNo))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Ce qui déclenche le Yes / No après réflexion", width=WIDTH, height=HEIGHT
)

fig.show()

In [273]:
# Colonnes des traits attribués au partenaire
trait_cols = ['attr', 'sinc', 'intel', 'fun', 'amb', 'shar']

# Labels lisibles
trait_labels = {
    'attr': 'Attractivité',
    'sinc': 'Sincérité',
    'intel': 'Intelligence',
    'fun': 'Fun / Humour',
    'amb': 'Ambition',
    'shar': 'Centres d\'intérêt'
}

# Filtrer les deux groupes
df_yes = df[df['dec'] == 1]
df_no = df[df['dec'] == 0]

# Calculer les moyennes
mean_yes = df_yes[trait_cols].mean().reset_index()
mean_yes.columns = ['Critère', 'Oui']

mean_no = df_no[trait_cols].mean().reset_index()
mean_no.columns = ['Critère', 'Non']

# Remplacer les noms techniques par des labels lisibles
mean_yes['Critère'] = mean_yes['Critère'].map(trait_labels)
mean_no['Critère'] = mean_no['Critère'].map(trait_labels)

# Fusionner les deux
radar_df = pd.merge(mean_yes, mean_no, on='Critère')

# Radar Chart pour les deux groupes
fig = go.Figure()

# Pour 'Oui'
fig.add_trace(go.Scatterpolar(
    r=radar_df['Oui'],
    theta=radar_df['Critère'],
    fill='toself',
    name='Oui (dec == 1)',
    line_color='#1E90FF'
))

# Pour 'Non'
fig.add_trace(go.Scatterpolar(
    r=radar_df['Non'],
    theta=radar_df['Critère'],
    fill='toself',
    name='Non (dec == 0)',
    line_color='#FF69B4'
))

# Mise en page du radar chart
fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, radar_df[['Oui', 'Non']].max().max() + 5])),
    showlegend=True,
    title="Profil des traits recherchés selon la décision de matcher",
    legend_title_text='Décision'
)

fig.show()

In [274]:
# Colonnes représentant les critères d'importance après décision (sur 100 points)
value_YesNo = ["attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", "shar7_2"]

# Labels lisibles pour les critères
labels_YesNo = {
    "attr7_2": "Attractivité",
    "sinc7_2": "Sincérité",
    "intel7_2": "Intelligence",
    "fun7_2": "Fun / Humour",
    "amb7_2": "Ambition",
    "shar7_2": "Centres d'intérêt"
}



# 🔍 Filtrer uniquement les participants qui ont dit "oui" pour matcher
df_yes = df[df['dec'] == 1]

# Transformer en format long pour Plotly
df_melted = df_yes.melt(id_vars=["gender"],
                        value_vars=value_YesNo,
                        var_name="Critère",
                        value_name="Points")

# Remplacer les noms des colonnes par des labels lisibles
df_melted["Critère"] = df_melted["Critère"].map(labels_YesNo)

# Calculer les moyennes par genre et par critère
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart interactif
fig = go.Figure()

# Couleurs personnalisées
colors = {
    "FEMALE": "#FF69B4",  # Rose
    "MALE": "#1E90FF"     # Bleu
}

# Ajouter une trace par genre
for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre : {gender}",
        line_color=colors.get(gender, "grey")
    ))

# Mise en page du radar chart
fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max() + 10])),
    showlegend=True,
    title="Ce qui déclenche le Yes (décision == 1) – Ventilation par genre",
    legend_title_text='Genre'
)

fig.show()

In [275]:
# Colonnes représentant les critères d'importance après décision (sur 100 points)
value_YesNo = ["attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", "shar7_2"]

# Labels lisibles pour les critères
labels_YesNo = {
    "attr7_2": "Attractivité",
    "sinc7_2": "Sincérité",
    "intel7_2": "Intelligence",
    "fun7_2": "Fun / Humour",
    "amb7_2": "Ambition",
    "shar7_2": "Centres d'intérêt"
}


# 🔍 Filtrer uniquement les participants qui ont dit "oui" pour matcher
df_yes = df[df['dec'] == 0]

# Transformer en format long pour Plotly
df_melted = df_yes.melt(id_vars=["gender"],
                        value_vars=value_YesNo,
                        var_name="Critère",
                        value_name="Points")

# Remplacer les noms des colonnes par des labels lisibles
df_melted["Critère"] = df_melted["Critère"].map(labels_YesNo)

# Calculer les moyennes par genre et par critère
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart interactif
fig = go.Figure()

# Couleurs personnalisées
colors = {
    "FEMALE": "#FF69B4",  # Rose
    "MALE": "#1E90FF"     # Bleu
}

# Ajouter une trace par genre
for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre : {gender}",
        line_color=colors.get(gender, "grey")
    ))

# Mise en page du radar chart
fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max() + 10])),
    showlegend=True,
    title="Ce qui déclenche le Yes (décision == 1) – Ventilation par genre",
    legend_title_text='Genre'
)

fig.show()

In [276]:
# A la moitié de l'expérience

value_soi_half= ["attr3_s", "sinc3_s", "intel3_s", "fun3_s", "amb3_s"]

# Définir les nouveaux labels pour l'axe des x

labels_soi= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_soi_half,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_soi_half, labels_soi))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Ce que l'on pense de soi à la moitié de l'expérience", width=WIDTH, height=HEIGHT
)

fig.show()

In [277]:
# Perception de soi le jour d'après le dating

value_soi_dayafter= ["attr3_2", "sinc3_2", "intel3_2", "fun3_2", "amb3_2"]

# Définir les nouveaux labels pour l'axe des x

labels_soi= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_soi_dayafter,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_soi_dayafter, labels_soi))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Ce que l'on pense de soi le jour d'après", width=WIDTH, height=HEIGHT
)

fig.show()

In [278]:
# Perception de soi le jour d'après le dating

value_soi_dayafter= ["attr5_2", "sinc5_2", "intel5_2", "fun5_2", "amb5_2"]

# Définir les nouveaux labels pour l'axe des x

labels_soi= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_soi_dayafter,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_soi_dayafter, labels_soi))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Le jour d'après : que pensent les autres de vous ?", width=WIDTH, height=HEIGHT
)

fig.show()

In [279]:
# Perception de soi le jour d'après le dating

value_soi_dayafter= ["attr1_2", "sinc1_2", "intel1_2", "fun1_2", "amb1_2"]

# Définir les nouveaux labels pour l'axe des x

labels_soi= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_soi_dayafter,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_soi_dayafter, labels_soi))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Jour d'après le date : que recherche-t-on ?", width=WIDTH, height=HEIGHT
)

fig.show()

In [280]:
# Perception de soi le jour d'après le dating

value_soi_dayafter= ["attr4_2", "sinc4_2", "intel4_2", "fun4_2", "amb4_2"]

# Définir les nouveaux labels pour l'axe des x

labels_soi= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_soi_dayafter,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_soi_dayafter, labels_soi))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Le jour d'après le date : que pensez-vous que les autres personnes du même sexe recherchent ?", width=WIDTH, height=HEIGHT
)

fig.show()

In [281]:
# Perception de soi le jour d'après le dating

value_soi_dayafter= ["attr2_2", "sinc2_2", "intel2_2", "fun2_2", "amb2_2"]

# Définir les nouveaux labels pour l'axe des x

labels_soi= ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_soi_dayafter,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_soi_dayafter, labels_soi))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Le jour d'après le date : que pensez-vous que la personne du sexe opposé recheche ? ", width=WIDTH, height=HEIGHT
)

fig.show()

In [282]:
# filtre Yes
yes_filter = df[df['match'] == 1].copy()

In [283]:
yes_filter['order'] = yes_filter['order'].astype(str)

In [284]:
df_order_yes = yes_filter['order'].value_counts().to_frame().reset_index()

In [285]:
px.bar(df_order_yes, x="order", y="count", color="count", text="count", width=1400, height=600, title = "Ordre de passage vs Matching")

In [286]:
# Ce que les autres pensent de vous

x = ["attr5_1", "sinc5_1", "intel5_1", "fun5_1", "amb5_1"]

# Définir les nouveaux labels pour l'axe des x

nouveaux_labels_o = ["Attractivité ", "Sincérité ", "Intelligence ", "Fun ", "Ambition "]

fig = px.box(df, x,
             color = "gender",
            title= "Critères d'attraction : <b>ce que les autres pensent de vous 🤩...</b> ",
            labels=nouveaux_labels_o, width=WIDTH, height=HEIGHT, color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE})


# Mettre à jour les labels de l'axe des x
fig.update_layout(
    yaxis=dict(
        tickmode='array',  # Utiliser un tableau personnalisé pour les ticks
        tickvals=x,       # Les valeurs actuelles de l'axe des x
        ticktext=nouveaux_labels_o, # Les nouveaux labels correspondants
        title_text="Critères d'attraction"  # Titre de l'axe X 
    ),
     xaxis=dict(
        title_text="Points"  # Titre de l'axe Y
)
)
fig.show()

In [287]:
import plotly.graph_objects as go

value_vars = ["attr1_1", "sinc1_1", "intel1_1", "fun1_1", "amb1_1", "shar1_1"]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_vars,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_vars, nouveaux_labels_o))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Souhaits des Utilisateurs avant le Dating", width=WIDTH, height=HEIGHT
)

fig.show()

In [288]:
import plotly.graph_objects as go

# After date want to match
value_vars_bfm = ["attr", "sinc", "intel", "fun", "amb", "shar"]

after_match = df[df['dec'] == 1]
df_melted = after_match.melt(id_vars=["gender"], 
                    value_vars=value_vars_bfm,
                    var_name="Critère", 
                    value_name="Points")


# Créer un dictionnaire de mapping
label_map = dict(zip(value_vars_bfm, nouveaux_labels_o))

# Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="L'Utilisateur souhaite revoir la personne et juge ses critères", width=WIDTH, height=HEIGHT
)

fig.show()

In [289]:

value_vars = ["attr1_1", "sinc1_1", "intel1_1", "fun1_1", "amb1_1", "shar1_1"]

# Supposons que df est votre DataFrame
df_melted = df.melt(id_vars=["gender"], 
                    value_vars=value_vars,
                    var_name="Critère", 
                    value_name="Points")


# 2. Créer un dictionnaire de mapping
label_map = dict(zip(value_vars, nouveaux_labels_o))

# 3. Remplacer les anciens noms par les nouveaux labels dans la colonne "Critère"
df_melted["Critère"] = df_melted["Critère"].map(label_map)

# Agréger les données par genre
df_radar = df_melted.groupby(["gender", "Critère"], as_index=False)["Points"].mean()

# Créer le radar chart
fig = go.Figure()

for gender in df_radar["gender"].unique():
    df_gender = df_radar[df_radar["gender"] == gender]
    if gender == "FEMALE":
        color = FEMALE  
    elif gender == "MALE":
        color = MALE 
    else:
        color = "grey"  

    fig.add_trace(go.Scatterpolar(
        r=df_gender["Points"],
        theta=df_gender["Critère"],
        fill='toself',
        name=f"Genre {gender}",
        line_color=color
    ))

fig.update_layout(
    polar=dict(radialaxis=dict(visible=True, range=[0, df_radar["Points"].max()])),
    title="Souhaits des Utilisateurs avant le Dating", width=WIDTH, height=HEIGHT
)

fig.show()

In [290]:

# Vérifier que les colonnes existent
if 'match' in df.columns and 'match_es' in df.columns:

    # Calculer les moyennes globales
    mean_real = df['match'].mean()
    mean_estimated = df['match_es'].mean()

    # Créer un DataFrame pour Plotly
    comparison_df = pd.DataFrame({
        'Type': ['Match Réel', 'Match Estimé'],
        'Moyenne': [mean_real, mean_estimated]
    })

    # Afficher le graphique à barres
    fig = px.bar(
        comparison_df,
        x='Type',
        y='Moyenne',
        title="Comparaison : Match Réel vs Match Estimé",
        labels={'Moyenne': 'Moyenne (sur échelle)', 'Type': 'Type de match'},
        color='Type',
        color_discrete_map={'Match Réel': FEMALE, 'Match Estimé': MALE},
        width=700,
        height=500, 
    )

    fig.update_layout(showlegend=False)
    fig.show()

else:
    print("Les colonnes 'match' et/ou 'match_es' ne sont pas présentes dans le dataset.")

In [291]:

# Vérifier si les colonnes existent
if 'match' in df.columns and 'match_es' in df.columns and 'gender' in df.columns:
    # Calculer les moyennes par genre
    mean_real_female = df[df['gender'] == 'FEMALE']['match'].mean()
    mean_estimated_female = df[df['gender'] == 'FEMALE']['match_es'].mean()
    mean_real_male = df[df['gender'] == 'MALE']['match'].mean()
    mean_estimated_male = df[df['gender'] == 'MALE']['match_es'].mean()

    print(f"Moyennes calculées : FEMALE (Match Réel: {mean_real_female}, Match Estimé: {mean_estimated_female}), MALE (Match Réel: {mean_real_male}, Match Estimé: {mean_estimated_male})")

    # Créer un DataFrame pour Plotly
    comparison_df = pd.DataFrame({
        'Type': ['Match Réel', 'Match Estimé', 'Match Réel', 'Match Estimé'],
        'Moyenne': [
            mean_real_female,
            mean_estimated_female,
            mean_real_male,
            mean_estimated_male
        ],
        'Genre': ['FEMALE', 'FEMALE', 'MALE', 'MALE']
    })

    print("DataFrame pour Plotly :")
    print(comparison_df)

    # Afficher le graphique à barres groupées
    fig = px.bar(
        comparison_df,
        x='Type',
        y='Moyenne',
        color='Genre',
        barmode='group',
        title="Comparaison : Match Réel vs Match Estimé (Ventilation par genre)",
        labels={'Moyenne': 'Moyenne (sur échelle)', 'Type': 'Type de match'},
        color_discrete_map={'FEMALE': FEMALE, 'MALE': MALE}, 
        width=800,
        height=500, 
    )
    fig.update_layout(
        legend_title_text='Genre',
        showlegend=True
    )
    fig.show()
else:
    print("Les colonnes 'match', 'match_es' ou 'gender' ne sont pas présentes dans le dataset.")

Moyennes calculées : FEMALE (Match Réel: 0.16923956546598057, Match Estimé: 2.8887020847343643), MALE (Match Réel: 0.1726689689195856, Match Estimé: 3.4979375368296997)
DataFrame pour Plotly :
           Type   Moyenne   Genre
0    Match Réel  0.169240  FEMALE
1  Match Estimé  2.888702  FEMALE
2    Match Réel  0.172669    MALE
3  Match Estimé  3.497938    MALE

In [292]:
# Filtrer les données pour un genre spécifique (par exemple, gender = 'MALE')
df_gender_0 = df[df["gender"] == 'MALE']

# Nouveaux labels pour les colonnes
nouveaux_labels = {
    "attr1_1": "Attractivité",
    "sinc1_1": "Sincérité",
    "intel1_1": "Intelligence",
    "fun1_1": "Fun",
    "amb1_1": "Ambition",
    "shar1_1": "Centres d'intérêt communs"
}

# Calculer la somme des valeurs pour chaque critère
sum_values = df_gender_0[nouveaux_labels.keys()].sum()

# Identifier le nom du critère avec la plus grande valeur
max_criterion = sum_values.idxmax()

# Créer une liste pour le paramètre pull
pull_list = [0.1 if col == max_criterion else 0 for col in nouveaux_labels.keys()]

# Créer le pie plot avec le morceau ayant la plus grosse valeur séparé
fig = px.pie(
    df_gender_0,
    values=sum_values,  # Somme des points pour chaque critère
    names=nouveaux_labels.values(),  # Utiliser les nouveaux labels pour les noms
    title="Répartition des points données par les hommes",
)

# Appliquer le paramètre pull
fig.update_traces(pull=pull_list)
fig.update_traces(textposition='inside', textinfo='label+percent')

fig.show()

In [293]:
# Filtrer les données pour un genre spécifique (par exemple, gender = 'MALE')
df_gender_0 = df[df["gender"] == 'FEMALE']

# Nouveaux labels pour les colonnes
nouveaux_labels = {
    "attr1_1": "Attractivité",
    "sinc1_1": "Sincérité",
    "intel1_1": "Intelligence",
    "fun1_1": "Fun",
    "amb1_1": "Ambition",
    "shar1_1": "Centres d'intérêt communs"
}

# Calculer la somme des valeurs pour chaque critère
sum_values = df_gender_0[nouveaux_labels.keys()].sum()

# Identifier le nom du critère avec la plus grande valeur
max_criterion = sum_values.idxmax()

# Créer une liste pour le paramètre pull
pull_list = [0.1 if col == max_criterion else 0 for col in nouveaux_labels.keys()]

# Créer le pie plot avec le morceau ayant la plus grosse valeur séparé
fig = px.pie(
    df_gender_0,
    values=sum_values,  # Somme des points pour chaque critère
    names=nouveaux_labels.values(),  # Utiliser les nouveaux labels pour les noms
    title="Répartition des points par les femmes",
)

# Appliquer le paramètre pull
fig.update_traces(pull=pull_list)
fig.update_traces(textposition='inside', textinfo='label+percent')
fig.show()

In [294]:
#df.to_csv("df.csv")

In [295]:

# Colonnes des traits attribués au partenaire
trait_cols = ['attr', 'sinc', 'intel', 'fun', 'amb', 'shar']

# Vérifier que les colonnes existent
for col in trait_cols + ['dec']:
    if col not in df.columns:
        raise ValueError(f"La colonne '{col}' est manquante dans le dataset.")

# Séparer les groupes selon la décision
df_yes = df[df['dec'] == 1]  # Veut revoir
df_no = df[df['dec'] == 0]    # Ne veut pas revoir

# Calculer les moyennes des traits par décision
mean_yes = df_yes[trait_cols].mean().reset_index()
mean_yes['Decision'] = 'Veut revoir'

mean_no = df_no[trait_cols].mean().reset_index()
mean_no['Decision'] = 'Ne veut pas revoir'

# Concaténer pour affichage
mean_comparison = pd.concat([mean_yes, mean_no], axis=0)
mean_comparison.columns = ['Critère', 'Moyenne', 'Decision']

# Mapping des noms des critères pour plus de lisibilité
trait_labels = {
    'attr': 'Attractivité',
    'sinc': 'Sincérité',
    'intel': 'Intelligence',
    'fun': 'Fun / Humour',
    'amb': 'Ambition',
    'shar': 'Centres d\'intérêt'
}

mean_comparison['Critère'] = mean_comparison['Critère'].map(trait_labels)

# Afficher le graphique à barres groupées
fig = px.bar(
    mean_comparison,
    x='Critère',
    y='Moyenne',
    color='Decision',
    barmode='group',
    title="Critères attribués selon la décision de revoir la personne",
    labels={'Moyenne': 'Points moyens attribués', 'Critère': 'Critère d\'attraction'},
    color_discrete_map={'Veut revoir': '#1E90FF', 'Ne veut pas revoir': '#FF69B4'},
    width=1000,
    height=600
)

fig.update_layout(xaxis_tickangle=-45)
fig.show()

In [296]:
import pandas as pd
import plotly.express as px



# Colonnes d'auto-perception (ce que je pense de moi)
self_cols = {
    'attr3_1': 'Attractivité',
    'sinc3_1': 'Sincérité',
    'intel3_1': 'Intelligence',
    'fun3_1': 'Fun',
    'amb3_1': 'Ambition'
}

# Colonnes de perception extérieure (ce que les autres pensent de moi)
others_cols = {
    'attr5_1': 'Attractivité',
    'sinc5_1': 'Sincérité',
    'intel5_1': 'Intelligence',
    'fun5_1': 'Fun',
    'amb5_1': 'Ambition'
}

# Créer les deux DataFrames
self_ratings = df[list(self_cols.keys())].copy()
self_ratings.rename(columns=self_cols, inplace=True)
self_ratings = self_ratings.mean().reset_index()
self_ratings.columns = ['Critère', 'Moyenne_Moi']

others_ratings = df[list(others_cols.keys())].copy()
others_ratings.rename(columns=others_cols, inplace=True)
others_ratings = others_ratings.mean().reset_index()
others_ratings.columns = ['Critère', 'Moyenne_Autres']

# Fusionner les deux DataFrames
comparison_df = pd.merge(self_ratings, others_ratings, on='Critère')

# Calculer la différence en valeur absolue et en pourcentage
comparison_df['Écart_absolu'] = abs(comparison_df['Moyenne_Moi'] - comparison_df['Moyenne_Autres'])
comparison_df['Écart_en_pourcentage'] = (comparison_df['Moyenne_Moi'] / comparison_df['Moyenne_Autres'] - 1) * 100
# Si "Moyenne_Autres" = 0, éviter la division par zéro
comparison_df['Écart_en_pourcentage'] = comparison_df['Écart_en_pourcentage'].replace([float('inf'), float('-inf')], 0)

# Afficher le résultat
print("Comparaison entre ce que l'on pense de soi et ce que les autres pensent :")
print(comparison_df.round(2))

# Afficher un graphique à barres groupées
# Afficher un graphique à barres groupées
fig = px.bar(
    comparison_df.melt(id_vars='Critère', value_vars=['Moyenne_Moi', 'Moyenne_Autres']),
    x='Critère',
    y='value',
    color='variable',
    barmode='group',
    title="Ce que je pense de moi vs Ce que les autres pensent de moi",
    labels={'value': 'Note moyenne (sur 10)', 'variable': 'Type d’évaluation'},
    color_discrete_map={'Moyenne_Moi': MALE, 'Moyenne_Autres': FEMALE},
    width=1400,
    height=600
)

fig.update_layout(xaxis_tickangle=-45)
fig.show()

Comparaison entre ce que l'on pense de soi et ce que les autres pensent :
        Critère  Moyenne_Moi  Moyenne_Autres  Écart_absolu  \
0  Attractivité         7.01            6.96          0.05
1     Sincérité         8.07            7.73          0.34
2  Intelligence         8.38            8.25          0.12
3           Fun         7.49            7.26          0.23
4      Ambition         7.38            7.51          0.13

   Écart_en_pourcentage
0                  0.79
1                  4.36
2                  1.51
3                  3.16
4                 -1.79

In [297]:

# Vérifier que les colonnes existent
if 'iid' in df.columns and 'wave' in df.columns:

    # Compter combien de vagues a fréquentées chaque participant
    participants_vagues = df.groupby('iid')['wave'].nunique().reset_index()
    participants_vagues.columns = ['Participant ID', 'Nombre de vagues']

    # Filtrer ceux qui apparaissent dans plus d'une vague
    multiples = participants_vagues[participants_vagues['Nombre de vagues'] > 1]

    print("Participants présents dans plusieurs vagues :")
    print(multiples.sort_values(by='Nombre de vagues', ascending=False).head(10))

else:
    print("Les colonnes 'iid' ou 'wave' ne sont pas présentes dans le dataset.")

Participants présents dans plusieurs vagues :
Empty DataFrame
Columns: [Participant ID, Nombre de vagues]
Index: []

In [298]:
# Vérifier que les colonnes existent
if 'you_call' in df.columns and 'them_cal' in df.columns and 'gender' in df.columns:

    # Calculer les moyennes par genre
    df['you_call'] = pd.to_numeric(df['you_call'], errors='coerce')
    df['them_cal'] = pd.to_numeric(df['them_cal'], errors='coerce')

    # Agréger les données par genre
    comparison = df.groupby('gender')[['you_call', 'them_cal']].mean().reset_index()

    # Renommer les colonnes pour plus de lisibilité
    comparison = comparison.melt(id_vars='gender', var_name='Type', value_name='Moyenne')
    comparison['Type'] = comparison['Type'].replace({
        'you_call': 'Nombre de matchs contactés',
        'them_cal': 'Nombre de matchs reçus'
    })

    # Afficher le graphique à barres groupées
    fig = px.bar(
        comparison,
        x='gender',
        y='Moyenne',
        color='Type',
        barmode='group',
        title="Comparaison : nombre moyen de matchs <b>contactés</b> vs <b>reçus</b> selon le genre",
        labels={'Moyenne': 'Nombre moyen de matchs', 'gender': 'Genre', 'Type': 'Type de contact'},
        color_discrete_map={
            'Nombre de matchs contactés': MALE,
            'Nombre de matchs reçus': FEMALE
        },
        width=1400,
        height=600
    )

    fig.update_layout(
        legend_title_text='Type de contact',
        xaxis_title="Genre",
        yaxis_title="Nombre moyen"
    )

    fig.show()

else:
    print("Les colonnes 'you_call', 'them_cal' ou 'gender' ne sont pas présentes dans le dataset.")